select * from KB_MUSTERIBILGILERI;

INSERT INTO
KB_MUSTERIBILGILERI (AD, SOYAD, EPOSTA, SIFRE, DOGUMTARIHI, TELEFONNO, TCKN, CINSIYET, MUSTERITIPI, SUBESUBEKODU, DURUMKODU, UNVAN, KAYITOLUSTURMATARIHI)
VALUES ('Aybey','Nurçin', 'aybeynurcin@gmail.com', 'aybey123', to_date('25082003','ddmmyy'),05376255784,11111111111,1,1,'S0010',1,'Müşteri',to_date('20072026','ddmmyy'));

alter table KB_MUSTERIBILGILERI MODIFY VKN NULL;

SELECT * FROM KB_MUSTERIBILGILERI;

COMMIT;

ALTER TABLE KB_PERSONEL MODIFY EPOSTA VARCHAR2(50);
