select * from KB_MUSTERIBILGILERI;

INSERT INTO
KB_MUSTERIBILGILERI (AD, SOYAD, EPOSTA, SIFRE, DOGUMTARIHI, TELEFONNO, TCKN, CINSIYET, MUSTERITIPI, SUBESUBEKODU, DURUMKODU, UNVAN, KAYITOLUSTURMATARIHI)
VALUES ('Aybey','Nurçin', 'aybeynurcin@gmail.com', 'aybey123', to_date('25082003','ddmmyy'),05376255784,11111111111,1,1,'S0010',1,'Müşteri',to_date('20072026','ddmmyy'));

alter table KB_MUSTERIBILGILERI MODIFY VKN NULL;

SELECT * FROM KB_MUSTERIBILGILERI;

COMMIT;

ALTER TABLE KB_PERSONEL MODIFY EPOSTA VARCHAR2(50);

INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Beşiktaş', '02122581234', 'Barbaros Bulvarı', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Şişli', '02122246789', 'Halaskargazi Cad.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Beyoğlu', '02122491122', 'İstiklal Caddesi', 2, 'MEHMET', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Fatih', '02125345678', 'Vatan Caddesi', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Sarıyer', '02122421357', 'Maslak Mah.', 1, 'AYSE', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Zeytinburnu', '02126641234', 'Kazlıçeşme Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Bakırköy', '02125437890', 'Sahil Yolu', 1, 'CANAN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Ataşehir', '02166871234', 'Batı Ataşehir', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Maltepe', '02163831234', 'Bağlarbaşı Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Pendik', '02163541234', 'Yayalar Mah.', 1, 'BURAK', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Kartal', '02163871234', 'Soğanlık Yeni Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Ümraniye 2', '02163161234', 'Çakmak Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Sultanbeyli', '02166931234', 'Mecidiye Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Tuzla', '02163951234', 'Aydınlı Mah.', 1, 'DENIZ', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Çekmeköy', '02166411234', 'Merkez Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Beykoz', '02163221234', 'Kavacık Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Şile', '02167111234', 'Çeşmeler Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Silivri', '02127281234', 'Fatih Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Çatalca', '02127891234', 'Ferhatpaşa Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Arnavutköy', '02126821234', 'Hadımköy', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Başakşehir 2', '02124871234', 'Kayabaşı Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Sultangazi', '02126171234', '75. Yıl Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Gaziosmanpaşa', '02125781234', 'Merkez Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Eyüpsultan', '02126211234', 'Rami Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Bahçelievler', '02126521234', 'Şirinevler Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Bağcılar', '02124351234', 'Kirazlı Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Güngören', '02125531234', 'Merter Mah.', 2, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Esenyurt', '02126211235', 'Yeşilkent Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Avcılar', '02126931234', 'Firuzköy Mah.', 1, 'ADMIN', SYSDATE);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU, RECORDUSER, RECORDDATE) VALUES ('Küçükçekmece', '02124251234', 'Halkalı Mah.', 2, 'ADMIN', SYSDATE);

insert into kb_musteriiletisim (musteribilgileriid, telefonno, eposta) values (44, '05376255784','aybey.nurcin@kocerbank.com');

INSERT INTO KB_MUSTERIILETISIM (TELEFONNO, EVTELEFON, ISTELEFON, EVADRES, ISADRES, EPOSTA, MUSTERIBILGILERIID, RECORDUSER, RECORDDATE) VALUES ('05376255784', NULL, NULL, NULL, NULL, 'aybey.nurcin@kocerbank.com', 44, 'ADMIN', SYSDATE);

select * from KB_musteriiletisim;
select * from KB_MUSTERIBILGILERI;

COMMIT;