INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES ('Merkez Şube', '02121234567', 'İstanbul, Türkiye', 1);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES ('Ümraniye Şube','02121234568', 'İstanbul, Türkiye', 1);
COMMIT;

INSERT INTO KB_PERSONEL (AD, SOYAD, ROL, SIFRE, TCKN, TELEFONNO, ADRES, EPOSTA, SUBESUBEKODU, DURUMKODU) VALUES ('Metehan', 'Ünal', 'Admin', 'admin123', 12345678901, '05551234567', 'İstanbul, Türkiye', 'metehan.unal@kocerbank.com', 'S0008', 1);
INSERT INTO KB_PERSONEL (AD, SOYAD, ROL, SIFRE, TCKN, TELEFONNO, ADRES, EPOSTA, SUBESUBEKODU, DURUMKODU) VALUES ('Ahmet', '7abak', 'Admin', 'admin123', 12345678902, '05551234568', 'İstanbul, Türkiye', 'ahmet.7abak@kocerbank.com', 'S0009', 1);


UPDATE KB_PERSONEL SET AD = 'Metehan' WHERE ID = 3;
COMMIT;

SELECT * FROM KB_PERSONEL;
SELECT * FROM KB_SUBE;



DELETE FROM KB_SUBE;
