INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES ('Merkez Şube', '02121234567', 'İstanbul, Türkiye', 1);
INSERT INTO KB_SUBE (SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES ('Ümraniye Şube','02121234568', 'İstanbul, Türkiye', 1);

INSERT INTO KB_PERSONEL (AD, SOYAD, ROL, SIFRE, TCKN, TELEFONNO, ADRES, EPOSTA, SUBESUBEKODU, DURUMKODU) VALUES ('MeteHAN', 'Ünal', 'Admin', 'admin123', 12345678901, '05551234567', 'İstanbul, Türkiye', 'metehan.unal@kocerbank.com', 'S0006', 1);


SELECT * FROM KB_PERSONEL;
SELECT * FROM KB_SUBE;



DELETE FROM KB_SUBE;
