tempid = KB_PERSONEL_SEQ.NEXTVAL;
tempid2 = KB_SUBE_SEQ.NEXTVAL;

INSERT INTO KB_PERSONEL (ID, AD, SOYAD, ROL, SICIL, SIFRE, TCKN, TELEFONNO, ADRES, EPOSTA, SUBESUBEKODU, DURUMKODU) VALUES (tempid, 'Ahmet', 'Tabak', 'Yönetici', KB_SICIL_SEQ.NEXTVAL, 'sifre123', 12345678901, '05551234567', 'İstanbul, Türkiye', 'ahmet.tabak@kocerbank.com', 'S0001', 1);
tempid2 = KB_SUBE_SEQ.NEXTVAL;
INSERT INTO KB_PERSONEL (ID, AD, SOYAD, ROL, SICIL, SIFRE, TCKN, TELEFONNO, ADRES, EPOSTA, SUBESUBEKODU, DURUMKODU) VALUES (KB_SUBE_SEQ.NEXTVAL, 'Metehan', 'Ünal', 'Yönetici', KB_SICIL_SEQ.NEXTVAL, 'sifre456', 23456789012, '05559876543', 'İstanbul, Türkiye', 'metehan.una@kocerbank.com', 'S0002', 1);

INSERT INTO KB_SUBE (ID, SUBEADI,  SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES (tempid2, 'Merkez Şube', '02121234567', 'İstanbul, Türkiye', 1);
INSERT INTO KB_SUBE (ID, SUBEADI, SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES (tempid2, 'Ümraniye Şube', KB_SUBEKODU_SEQ.NEXTVAL, '02121234568', 'İstanbul, Türkiye', 1);
INSERT INTO KB_SUBE (ID, SUBEADI,  SUBETELEFONNO, SUBEADRES, SUBEDURUMKODU) VALUES (KB_SUBE_SEQ.NEXTVAL, 'Merkez Şube', '02121234567', 'İstanbul, Türkiye', 1);

SELECT * FROM KB_PERSONEL;
SELECT * FROM KB_SUBE;

DELETE FROM KB_SUBE;