INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_CINSIYET', '1', 'ERKEK');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_CINSIYET', '2', 'KADIN');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_MUSTERITIPI', '1', 'BIREYSEL');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_MUSTERITIPI', '2', 'KURUMSAL');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_DURUMKODU', '1', 'AKTIF');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIBILGILERI_DURUMKODU', '2', 'PASIF');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '1', 'TELEFON NO');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '2', 'EV ADRESI');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '3', 'İŞ ADRESI');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '4', 'EV TELEFON NO');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '5', 'İŞ TELEFON NO');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_MUSTERIILETISIM_ILETISIMTIPI', '6', 'E-POSTA');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_DOVIZCINSI', '1', 'TL');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_DOVIZCINSI', '2', 'USD');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_DOVIZCINSI', '3', 'EUR');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPDURUMKODU', '1', 'AKTIF');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPDURUMKODU', '2', 'PASIF');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPDURUMKODU', '3', 'KAPALI');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPTIPI', '1', 'VADELİ');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPTIPI', '2', 'VADESİZ');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_HESAPBILGILERI_HESAPTIPI', '3', 'YATIRIM');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_SUBE_SUBEDURUMKODU', '1', 'AKTIF');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_SUBE_SUBEDURUMKODU', '2', 'PASIF');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PERSONEL_DURUMKODU', '1', 'AKTIF');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PERSONEL_DURUMKODU', '2', 'PASIF');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_TRANSFERTIPI', '1', 'HAVALE');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_TRANSFERTIPI', '2', 'EFT');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_TRANSFERTIPI', '3', 'SWIFT');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_GONDERENDOVIZTIPI', '1', 'TL');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_GONDERENDOVIZTIPI', '2', 'USD');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_GONDERENDOVIZTIPI', '3', 'EUR');

INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_ALICIDOVIZTIPI', '1', 'TL');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_ALICIDOVIZTIPI', '2', 'USD');
INSERT INTO KB_PARAMETRE (GRUPKODU, KODU, ACIKLAMA) VALUES ('KB_PARATRANSFERI_ALICIDOVIZTIPI', '3', 'EUR');

COMMIT;


select * from KB_PARAMETRE;


