CREATE SEQUENCE KB_MUSTERIBILGILERI_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

drop sequence KB_MUSTERIBILGILERI_SEQ;
drop sequence KB_MUSTERIILETISIM_SEQ;
drop sequence KB_HESAPBILGILERI_SEQ;
drop sequence KB_PARATRANSFERI_SEQ;
drop sequence KB_PERSONEL_SEQ;
drop sequence KB_SUBE_SEQ;
drop sequence KB_HESAPHAREKETI_SEQ;
drop sequence KB_SUBEKODU_SEQ;
drop sequence KB_SICIL_SEQ;
drop sequence KB_PARAMETRE_SEQ;
drop sequence KB_HESAPNO_SEQ;
drop sequence KB_HESAPHAREKETI_SEQ;


CREATE SEQUENCE KB_MUSTERIILETISIM_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_HESAPBILGILERI_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_SUBE_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_PERSONEL_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_PARATRANSFERI_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999999999999999999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_SUBEKODU_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_SICIL_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_PARAMETRE_SEQ 
START WITH 1 
INCREMENT BY 1 
MAXVALUE 9999
NOCYCLE 
NOCACHE;

CREATE SEQUENCE KB_HESAPHAREKETI_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP SEQUENCE KB_SUBEKODU_SEQ;
DROP SEQUENCE KB_SUBE_SEQ;
DROP SEQUENCE KB_PERSONEL_SEQ;
DROP SEQUENCE KB_SICIL_SEQ;


CREATE SEQUENCE KB_HESAPNO_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999
CYCLE
NOCACHE;
  
commit;