/* Dashboard tarih aralığı filtresi için KB_SUBE ve KB_PERSONEL tablolarına
   Müşteri'deki KAYITOLUSTURMATARIHI ile aynı isim ve desende yeni kolon. */

ALTER TABLE KB_SUBE ADD KAYITOLUSTURMATARIHI DATE DEFAULT SYSDATE NOT NULL;
ALTER TABLE KB_PERSONEL ADD KAYITOLUSTURMATARIHI DATE DEFAULT SYSDATE NOT NULL;
