CREATE TABLE KB_HESAPBILGILERI(
    ID                 NUMBER(19) DEFAULT ON NULL KB_HESAPBILGILERI_SEQ.NEXTVAL,
    HESAPADI           VARCHAR2(50)                                             NOT NULL,
    HESAPNO            VARCHAR2(16)                                             NOT NULL,
    IBAN               VARCHAR2(26) UNIQUE                                      NOT NULL,
    BAKIYE             NUMBER(14,2)                                             NOT NULL,
    SUBESUBEKODU       VARCHAR2(20)                                             NOT NULL,
    DOVIZCINSI         NUMBER(1) CHECK (DOVIZCINSI IN (1,2,3))                  NOT NULL,
    HESAPACILISTARIHI  DATE DEFAULT SYSDATE                                     NOT NULL,
    HESAPDURUMKODU     NUMBER(1) CHECK (HESAPDURUMKODU IN (1,2,3))              NOT NULL,
    MUSTERIBILGILERIID NUMBER(19)                                               NOT NULL,
    HESAPTIPI          NUMBER(1) CHECK (HESAPTIPI IN (1,2,3))                   NOT NULL,
    RECORDUSER         VARCHAR2(10),
    RECORDDATE         DATE DEFAULT SYSDATE,

    /* Hesap No 16 hane, IBAN 26 hane ve son 16 hanesi Hesap No */
    CONSTRAINT PK_KB_HESAPBILGILERI PRIMARY KEY (ID),
    CONSTRAINT FK_KB_HESAPBILGILERI_MUSTERIBILGILERIID FOREIGN KEY (MUSTERIBILGILERIID) REFERENCES KB_MUSTERIBILGILERI(ID) ON DELETE CASCADE
    
);

ALTER TABLE KB_HESAPBILGILERI
ADD CONSTRAINT FK_KB_HESAPBILGILERI_SUBE
FOREIGN KEY (SUBESUBEKODU)
REFERENCES KB_SUBE(SUBEKODU);

ALTER TABLE KB_HESAPBILGILERI
ADD CONSTRAINT UK_KB_HESAPBILGILERI_HESAPNO
UNIQUE (HESAPNO);

SELECT * FROM KB_HESAPBILGILERI;

CREATE TABLE KB_PARATRANSFERI(
    ID                 NUMBER(19) DEFAULT ON NULL KB_PARATRANSFERI_SEQ.NEXTVAL,
    GONDERENIBAN       VARCHAR2(26)                                             NOT NULL,
    ALICIIBAN          VARCHAR2(26)                                             NOT NULL,
    TRANSFERTIPI       NUMBER(1) CHECK (TRANSFERTIPI IN (1,2,3))                NOT NULL,
    MIKTAR             NUMBER(14,2)                                             NOT NULL,
    ACIKLAMA           VARCHAR2(100)                                            NOT NULL,
    GONDERENDOVIZTIPI  NUMBER(1) CHECK (GONDERENDOVIZTIPI IN (1,2,3))           NOT NULL,
    ALICIDOVIZTIPI     NUMBER(1) CHECK (ALICIDOVIZTIPI IN (1,2,3))              NOT NULL,
    TARIHSAAT          DATE DEFAULT SYSDATE                                     NOT NULL,
    RECORDDATE         DATE DEFAULT SYSDATE,
    RECORUSER          VARCHAR2(19),

    CONSTRAINT PK_KB_PARATRANSFERI PRIMARY KEY (ID),
    CONSTRAINT FK_KB_PARATRANSFERI_GONDERENIBAN FOREIGN KEY (GONDERENIBAN) REFERENCES KB_HESAPBILGILERI(IBAN) ON DELETE CASCADE,
    CONSTRAINT FK_KB_PARATRANSFERI_ALICIIBAN FOREIGN KEY (ALICIIBAN) REFERENCES KB_HESAPBILGILERI(IBAN) ON DELETE CASCADE
);

SELECT * FROM KB_PARATRANSFERI;

drop table kb_paratransferi;

SELECT KODU, ACIKLAMA
FROM KB_PARAMETRE
WHERE GRUPKODU = 'KB_HESAPBILGILERI_HESAPTIPI'
ORDER BY KODU;

CREATE TABLE KB_PARATRANSFERI
(
    ID NUMBER(19) DEFAULT ON NULL KB_PARATRANSFERI_SEQ.NEXTVAL NOT NULL,
    GONDERENHESAPID NUMBER(19) NOT NULL,
    ALICIHESAPID NUMBER(19) NOT NULL,
    TRANSFERTIPI NUMBER(1) NOT NULL,
    MIKTAR NUMBER(14,2) NOT NULL,
    GONDERENDOVIZTIPI NUMBER(1) NOT NULL,
    ALICIDOVIZTIPI NUMBER(1) NOT NULL,
    DOVIZKURU NUMBER(18,8) NOT NULL,
    ACIKLAMA VARCHAR2(100),
    TARIHSAAT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    RECORDUSER VARCHAR2(10),
    RECORDDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP,

    CONSTRAINT PK_KB_PARATRANSFERI PRIMARY KEY (ID),

    CONSTRAINT FK_KB_TRANSFER_GONDEREN FOREIGN KEY (GONDERENHESAPID) REFERENCES KB_HESAPBILGILERI(ID),

    CONSTRAINT FK_KB_TRANSFER_ALICI FOREIGN KEY (ALICIHESAPID) REFERENCES KB_HESAPBILGILERI(ID),

    CONSTRAINT CK_KB_TRANSFER_TIP CHECK (TRANSFERTIPI IN (1,2)),

    CONSTRAINT CK_KB_TRANSFER_MIKTAR CHECK (MIKTAR > 0),

    CONSTRAINT CK_KB_TRANSFER_GONDERENDOVIZ CHECK (GONDERENDOVIZTIPI IN (1,2,3)),

    CONSTRAINT CK_KB_TRANSFER_ALICIDOVIZ CHECK (ALICIDOVIZTIPI IN (1,2,3)),

    CONSTRAINT CK_KB_TRANSFER_KUR CHECK (DOVIZKURU > 0),

    CONSTRAINT CK_KB_TRANSFER_HESAPLAR CHECK (GONDERENHESAPID <> ALICIHESAPID),

    CONSTRAINT CK_KB_TRANSFER_AYNI_DOVIZ CHECK (GONDERENDOVIZTIPI <> ALICIDOVIZTIPI OR DOVIZKURU = 1)
);

ALTER TABLE KB_PARATRANSFERI
RENAME COLUMN MIKTAR TO GONDERENTUTAR;

/*
    EFT DESTEĞİ

    Havale/EFT ekranında alıcı IBAN'ı bizim
    bankamızda kayıtlı değilse işlem EFT olarak
    kaydedilir: ALICIHESAPID NULL kalır, alıcı
    IBAN'ı ve kullanıcının girdiği ad-soyad metin
    olarak ALICIIBAN/ALICIADSOYAD'a yazılır.

    ALICIIBAN 34 karakter olarak tanımlanır çünkü
    SWIFT ekranında yabancı (TR olmayan) IBAN'lar
    da bu koloa yazılabilir (bkz. SWIFT EFT desteği).
*/

ALTER TABLE KB_PARATRANSFERI
MODIFY (ALICIHESAPID NUMBER(19) NULL);

ALTER TABLE KB_PARATRANSFERI
ADD (
    ALICIIBAN    VARCHAR2(34),
    ALICIADSOYAD VARCHAR2(150)
);

ALTER TABLE KB_PARATRANSFERI
DROP CONSTRAINT CK_KB_TRANSFER_TIP;

ALTER TABLE KB_PARATRANSFERI
ADD CONSTRAINT CK_KB_TRANSFER_TIP
CHECK (TRANSFERTIPI IN (1,2,3));

ALTER TABLE KB_PARATRANSFERI
ADD CONSTRAINT CK_KB_TRANSFER_ALICI_TUTARLILIK
CHECK (
    (TRANSFERTIPI = 3 AND ALICIHESAPID IS NULL AND ALICIIBAN IS NOT NULL)
    OR
    (TRANSFERTIPI <> 3 AND ALICIHESAPID IS NOT NULL AND ALICIIBAN IS NULL)
);

select * from kb_paratransferi;


/*
    SWIFT EFT DESTEĞİ

    SWIFT ekranında da alıcı IBAN'ı bizim
    bankamızda kayıtlı değilse işlem, TransferTipi=4
    (SwiftEft) olarak kaydedilir. Havale/EFT'teki
    EFT'den (TransferTipi=3) farkı, alıcının döviz
    cinsinin bizim tarafımızdan bilinemeyip kullanıcı
    tarafından ekranda seçilmesi ve kurun bu seçime
    göre hesaplanmasıdır (kur her zaman 1 değildir).
*/

ALTER TABLE KB_PARATRANSFERI
DROP CONSTRAINT CK_KB_TRANSFER_TIP;

ALTER TABLE KB_PARATRANSFERI
ADD CONSTRAINT CK_KB_TRANSFER_TIP
CHECK (TRANSFERTIPI IN (1,2,3,4));

ALTER TABLE KB_PARATRANSFERI
DROP CONSTRAINT CK_KB_TRANSFER_ALICI_TUTARLILIK;

ALTER TABLE KB_PARATRANSFERI
ADD CONSTRAINT CK_KB_TRANSFER_ALICI_TUTARLILIK
CHECK (
    (TRANSFERTIPI IN (3,4) AND ALICIHESAPID IS NULL AND ALICIIBAN IS NOT NULL)
    OR
    (TRANSFERTIPI NOT IN (3,4) AND ALICIHESAPID IS NOT NULL AND ALICIIBAN IS NULL)
);

DROP TABLE KB_PARATRANSFERI;

CREATE TABLE KB_HESAPHAREKETI
(
    ID NUMBER(19) DEFAULT ON NULL KB_HESAPHAREKETI_SEQ.NEXTVAL NOT NULL,
    HESAPBILGILERIID NUMBER(19) NOT NULL,
    PARATRANSFERIID NUMBER(19),
    HAREKETTIPI NUMBER(1) NOT NULL,
    MIKTAR NUMBER(14,2) NOT NULL,
    DOVIZCINSI NUMBER(1) NOT NULL,
    ONCEKIBAKIYE NUMBER(14,2) NOT NULL,
    SONRAKIBAKIYE NUMBER(14,2) NOT NULL,
    ISLEMTARIHI TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    RECORDUSER VARCHAR2(10),
    RECORDDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP,

    CONSTRAINT PK_KB_HESAPHAREKETI PRIMARY KEY (ID),

    CONSTRAINT FK_KB_HAREKET_HESAP FOREIGN KEY (HESAPBILGILERIID) REFERENCES KB_HESAPBILGILERI(ID),

    CONSTRAINT FK_KB_HAREKET_TRANSFER FOREIGN KEY (PARATRANSFERIID) REFERENCES KB_PARATRANSFERI(ID),

    CONSTRAINT CK_KB_HAREKET_TIP CHECK (HAREKETTIPI IN (1,2,3,4)),

    CONSTRAINT CK_KB_HAREKET_DOVIZ CHECK (DOVIZCINSI IN (1,2,3)),

    CONSTRAINT CK_KB_HAREKET_BAKIYELER CHECK (ONCEKIBAKIYE >= 0 AND SONRAKIBAKIYE >= 0),

    CONSTRAINT CK_KB_HAREKET_TRANSFER CHECK (
        (HAREKETTIPI IN (1,2) AND PARATRANSFERIID IS NULL)
        OR
        (HAREKETTIPI IN (3,4) AND PARATRANSFERIID IS NOT NULL)
    ),

    CONSTRAINT CK_KB_HAREKET_BAKIYE_ISLEMI CHECK (
        (HAREKETTIPI IN (1,3) AND SONRAKIBAKIYE = ONCEKIBAKIYE + MIKTAR)
        OR
        (HAREKETTIPI IN (2,4) AND SONRAKIBAKIYE = ONCEKIBAKIYE - MIKTAR)
    )
);

drop table kb_hesaphareketi;

ALTER TABLE KB_HESAPHAREKETI
DROP CONSTRAINT UK_KB_HAREKET_TRANSFER_TIP;

select * from kb_hesaphareketleri;

drop table kb_hesaphareketleri;


