CREATE TABLE KB_PARAMETRE (
    ID NUMBER(19) DEFAULT ON NULL KB_PARAMETRE_SEQ.NEXTVAL NOT NULL PRIMARY KEY,
    GRUPKODU VARCHAR2(50) NOT NULL,
    KODU VARCHAR2(50) NOT NULL,
    ACIKLAMA VARCHAR2(100) NOT NULL,
    RECORDUSER VARCHAR2(10),
    RECORDDATE DATE DEFAULT SYSDATE
);