CREATE OR REPLACE PROCEDURE KB_PERSONEL_EKLE
(
    P_AD                IN  KB_PERSONEL.AD%TYPE,
    P_SOYAD             IN  KB_PERSONEL.SOYAD%TYPE,
    P_ROL               IN  KB_PERSONEL.ROL%TYPE,
    P_SIFRE             IN  KB_PERSONEL.SIFRE%TYPE,
    P_TCKN              IN  KB_PERSONEL.TCKN%TYPE,
    P_TELEFONNO         IN  KB_PERSONEL.TELEFONNO%TYPE,
    P_ADRES             IN  KB_PERSONEL.ADRES%TYPE,
    P_EPOSTA            IN  KB_PERSONEL.EPOSTA%TYPE,
    P_SUBEKODU          IN  KB_PERSONEL.SUBESUBEKODU%TYPE,
    P_DURUMKODU         IN  KB_PERSONEL.DURUMKODU%TYPE,
    P_RECORDUSER        IN  KB_PERSONEL.RECORDUSER%TYPE,

    P_ID                    OUT KB_PERSONEL.ID%TYPE,
    P_SICIL                 OUT KB_PERSONEL.SICIL%TYPE,
    P_KAYITOLUSTURMATARIHI  OUT KB_PERSONEL.KAYITOLUSTURMATARIHI%TYPE
)
AS
    V_RECORDUSER KB_PERSONEL.RECORDUSER%TYPE;
    V_RECORDDATE KB_PERSONEL.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    INSERT INTO KB_PERSONEL
    (
        AD,
        SOYAD,
        ROL,
        SIFRE,
        TCKN,
        TELEFONNO,
        ADRES,
        EPOSTA,
        SUBESUBEKODU,
        DURUMKODU,
        RECORDUSER,
        RECORDDATE
    )
    VALUES
    (
        P_AD,
        P_SOYAD,
        P_ROL,
        P_SIFRE,
        P_TCKN,
        P_TELEFONNO,
        P_ADRES,
        P_EPOSTA,
        P_SUBEKODU,
        P_DURUMKODU,
        V_RECORDUSER,
        V_RECORDDATE
    )
    RETURNING ID, SICIL, KAYITOLUSTURMATARIHI INTO P_ID, P_SICIL, P_KAYITOLUSTURMATARIHI;
END ;
/



CREATE OR REPLACE PROCEDURE KB_PERSONEL_GETIRBYID(
    P_ID            IN  KB_PERSONEL.ID%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM KB_PERSONEL WHERE ID = P_ID;
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_LISTELE
(
    P_ID          IN  KB_PERSONEL.ID%TYPE,
    P_AD          IN  KB_PERSONEL.AD%TYPE,
    P_SOYAD       IN  KB_PERSONEL.SOYAD%TYPE,
    P_ROL         IN  KB_PERSONEL.ROL%TYPE,
    P_TCKN        IN  KB_PERSONEL.TCKN%TYPE,
    P_TELEFONNO   IN  KB_PERSONEL.TELEFONNO%TYPE,
    P_SUBEKODU    IN  KB_PERSONEL.SUBESUBEKODU%TYPE,
    P_ADRES        IN  KB_PERSONEL.ADRES%TYPE,
    P_EPOSTA       IN  KB_PERSONEL.EPOSTA%TYPE,
    P_DURUMKODU    IN  KB_PERSONEL.DURUMKODU%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM KB_PERSONEL
    WHERE
            (ID             = P_ID OR P_ID IS NULL)
        AND (AD             = P_AD IS NULL OR UPPER(AD) LIKE '%' || UPPER(P_AD) || '%')
        AND (SOYAD          = P_SOYAD IS NULL OR UPPER(SOYAD) LIKE '%' || (P_SOYAD) || '%')
        AND (ROL            = P_ROL OR P_ROL IS NULL)
        AND (TCKN           = P_TCKN OR P_TCKN IS NULL)
        AND (TELEFONNO      = P_TELEFONNO OR P_TELEFONNO IS NULL)
        AND (SUBESUBEKODU   = P_SUBEKODU OR P_SUBEKODU IS NULL)
        AND (ADRES          = P_ADRES IS NULL OR UPPER(ADRES) LIKE '%' || UPPER(P_ADRES) || '%')
        AND (EPOSTA         = P_EPOSTA OR P_EPOSTA IS NULL)
        AND (DURUMKODU      = P_DURUMKODU OR P_DURUMKODU IS NULL);
END ;
/

CREATE OR REPLACE PROCEDURE KB_PERSONEL_LISTELE
(
    P_ID          IN  KB_PERSONEL.ID%TYPE,
    P_AD          IN  KB_PERSONEL.AD%TYPE,
    P_SOYAD       IN  KB_PERSONEL.SOYAD%TYPE,
    P_ROL         IN  KB_PERSONEL.ROL%TYPE,
    P_TCKN        IN  KB_PERSONEL.TCKN%TYPE,
    P_TELEFONNO   IN  KB_PERSONEL.TELEFONNO%TYPE,
    P_SUBEKODU    IN  KB_PERSONEL.SUBESUBEKODU%TYPE,
    P_ADRES       IN  KB_PERSONEL.ADRES%TYPE,
    P_EPOSTA      IN  KB_PERSONEL.EPOSTA%TYPE,
    P_DURUMKODU   IN  KB_PERSONEL.DURUMKODU%TYPE,

    P_CURSOR      OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM KB_PERSONEL
        WHERE
                (P_ID IS NULL OR ID = P_ID)
            AND (
                P_AD IS NULL
                OR UPPER(AD) LIKE
                    '%' || UPPER(P_AD) || '%'
            )
            AND (
                P_SOYAD IS NULL
                OR UPPER(SOYAD) LIKE
                    '%' || UPPER(P_SOYAD) || '%'
            )
            AND (
                P_ROL IS NULL
                OR ROL = P_ROL
            )
            AND (
                P_TCKN IS NULL
                OR TCKN = P_TCKN
            )
            AND (
                P_TELEFONNO IS NULL
                OR TELEFONNO = P_TELEFONNO
            )
            AND (
                P_SUBEKODU IS NULL
                OR SUBESUBEKODU = P_SUBEKODU
            )
            AND (
                P_ADRES IS NULL
                OR UPPER(ADRES) LIKE
                    '%' || UPPER(P_ADRES) || '%'
            )
            AND (
                P_EPOSTA IS NULL
                OR UPPER(EPOSTA) = UPPER(P_EPOSTA)
            )
            AND (
                P_DURUMKODU IS NULL
                OR DURUMKODU = P_DURUMKODU
            )
        ORDER BY
            KAYITOLUSTURMATARIHI DESC,
            ID DESC;
END KB_PERSONEL_LISTELE;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_GUNCELLE(
    P_ID            IN KB_PERSONEL.ID%TYPE,
    P_RECORDUSER    IN KB_PERSONEL.RECORDUSER%TYPE,
    P_AD            IN KB_PERSONEL.AD%TYPE              DEFAULT NULL,
    P_SOYAD         IN KB_PERSONEL.SOYAD%TYPE           DEFAULT NULL,
    P_ROL           IN KB_PERSONEL.ROL%TYPE             DEFAULT NULL,
    P_SIFRE         IN KB_PERSONEL.SIFRE%TYPE           DEFAULT NULL,
    P_TCKN          IN KB_PERSONEL.TCKN%TYPE            DEFAULT NULL,
    P_TELEFONNO     IN KB_PERSONEL.TELEFONNO%TYPE       DEFAULT NULL,
    P_ADRES         IN KB_PERSONEL.ADRES%TYPE           DEFAULT NULL,
    P_EPOSTA        IN KB_PERSONEL.EPOSTA%TYPE          DEFAULT NULL,
    P_SUBEKODU      IN KB_PERSONEL.SUBESUBEKODU%TYPE    DEFAULT NULL,
    P_DURUMKODU     IN KB_PERSONEL.DURUMKODU%TYPE       DEFAULT NULL
)
AS
    V_RECORDUSER KB_PERSONEL.RECORDUSER%TYPE;
    V_RECORDDATE KB_PERSONEL.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    UPDATE KB_PERSONEL
    SET AD              = NVL(P_AD, AD),
        SOYAD           = NVL(P_SOYAD, SOYAD),
        ROL             = NVL(P_ROL, ROL),
        SIFRE           = NVL(P_SIFRE, SIFRE),
        TCKN            = NVL(P_TCKN, TCKN),
        TELEFONNO       = NVL(P_TELEFONNO, TELEFONNO),
        ADRES           = NVL(P_ADRES, ADRES),
        EPOSTA          = NVL(P_EPOSTA, EPOSTA),
        SUBESUBEKODU    = NVL(P_SUBEKODU, SUBESUBEKODU),
        DURUMKODU       = NVL(P_DURUMKODU, DURUMKODU),
        RECORDUSER      = V_RECORDUSER,
        RECORDDATE      = V_RECORDDATE
    WHERE ID = P_ID;
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_SIL
(
    P_ID IN KB_PERSONEL.ID%TYPE
)
AS
BEGIN
    DELETE FROM KB_PERSONEL WHERE ID = P_ID;
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_GETIRBYSICIL(
    P_SICIL   IN  KB_PERSONEL.SICIL%TYPE,
    P_CURSOR  OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT *
    FROM KB_PERSONEL
    WHERE SICIL = P_SICIL;
END;
/










/* PARA TRANSFERİ PROSEDÜRÜ */

/*
 * NOT: Para transferi artık KB_PARA_TRANSFERI_YAP
 * (paratransferi.sql) üzerinden yapılmaktadır.
 * Buradaki KB_PARATRANSFERI_EKLE / KB_PARATRANSFERI_GUNCELLE
 * tanımları hiçbir yerden çağrılmadığı için kaldırılmıştır.
 */

CREATE OR REPLACE PROCEDURE KB_PARATRANSFERI_GETIRBYID
(
    P_ID        IN  KB_PARATRANSFERI.ID%TYPE,
    P_CURSOR    OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM KB_PARATRANSFERI
        WHERE ID = P_ID;
END;
/










/*
 * NOT: KB_HESAPBILGILERI_EKLE'nin güncel tanımı IBAN.sql
 * dosyasındadır (hesap no ve IBAN üretimini de yapar).
 * Buradaki eski kopya, IBAN.sql'den sonra çalıştırıldığında
 * canlı prosedürü bozduğu için kaldırılmıştır.
 */

CREATE OR REPLACE PROCEDURE KB_HESAPBILGILERI_GETIRBYID
(
    P_ID        IN KB_HESAPBILGILERI.ID%TYPE,

    P_SONUC     OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
    SELECT *
    FROM KB_HESAPBILGILERI
    WHERE ID = P_ID;
END KB_HESAPBILGILERI_GETIRBYID;
/





CREATE OR REPLACE PROCEDURE KB_HESAPBILGILERI_LISTELE
(
    P_ID                    IN KB_HESAPBILGILERI.ID%TYPE,
    P_HESAPADI              IN KB_HESAPBILGILERI.HESAPADI%TYPE,
    P_HESAPNO               IN KB_HESAPBILGILERI.HESAPNO%TYPE,
    P_IBAN                  IN KB_HESAPBILGILERI.IBAN%TYPE,
    P_BAKIYE                IN KB_HESAPBILGILERI.BAKIYE%TYPE,
    P_SUBESUBEKODU          IN KB_HESAPBILGILERI.SUBESUBEKODU%TYPE,
    P_DOVIZCINSI            IN KB_HESAPBILGILERI.DOVIZCINSI%TYPE,
    P_HESAPACILISTARIHI     IN KB_HESAPBILGILERI.HESAPACILISTARIHI%TYPE,
    P_HESAPDURUMKODU        IN KB_HESAPBILGILERI.HESAPDURUMKODU%TYPE,
    P_MUSTERIBILGILERIID    IN KB_HESAPBILGILERI.MUSTERIBILGILERIID%TYPE,
    P_HESAPTIPI             IN KB_HESAPBILGILERI.HESAPTIPI%TYPE,

    P_SONUC                 OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
    SELECT *
    FROM KB_HESAPBILGILERI
    WHERE
        (P_ID IS NULL OR ID = P_ID)
    AND (P_HESAPADI IS NULL OR UPPER(HESAPADI) LIKE '%' || UPPER(P_HESAPADI) || '%')
    AND (P_HESAPNO IS NULL OR HESAPNO = P_HESAPNO)
    AND (P_IBAN IS NULL OR IBAN = P_IBAN)
    AND (P_BAKIYE IS NULL OR BAKIYE = P_BAKIYE)
    AND (P_SUBESUBEKODU IS NULL OR SUBESUBEKODU = P_SUBESUBEKODU)
    AND (P_DOVIZCINSI IS NULL OR DOVIZCINSI = P_DOVIZCINSI)
    AND (P_HESAPACILISTARIHI IS NULL OR TRUNC(HESAPACILISTARIHI) = TRUNC(P_HESAPACILISTARIHI))
    AND (P_HESAPDURUMKODU IS NULL OR HESAPDURUMKODU = P_HESAPDURUMKODU)
    AND (P_MUSTERIBILGILERIID IS NULL OR MUSTERIBILGILERIID = P_MUSTERIBILGILERIID)
    AND (P_HESAPTIPI IS NULL OR HESAPTIPI = P_HESAPTIPI);
END KB_HESAPBILGILERI_LISTELE;
/






CREATE OR REPLACE PROCEDURE KB_HESAPBILGILERI_GUNCELLE
(
    P_ID                    IN KB_HESAPBILGILERI.ID%TYPE,
    P_RECORDUSER            IN KB_HESAPBILGILERI.RECORDUSER%TYPE,
    P_HESAPADI              IN KB_HESAPBILGILERI.HESAPADI%TYPE              DEFAULT NULL,
    P_HESAPNO               IN KB_HESAPBILGILERI.HESAPNO%TYPE               DEFAULT NULL,
    P_IBAN                  IN KB_HESAPBILGILERI.IBAN%TYPE                  DEFAULT NULL,
    P_BAKIYE                IN KB_HESAPBILGILERI.BAKIYE%TYPE                DEFAULT NULL,
    P_SUBESUBEKODU          IN KB_HESAPBILGILERI.SUBESUBEKODU%TYPE          DEFAULT NULL,
    P_DOVIZCINSI            IN KB_HESAPBILGILERI.DOVIZCINSI%TYPE            DEFAULT NULL,
    P_HESAPDURUMKODU        IN KB_HESAPBILGILERI.HESAPDURUMKODU%TYPE        DEFAULT NULL,
    P_MUSTERIBILGILERIID    IN KB_HESAPBILGILERI.MUSTERIBILGILERIID%TYPE    DEFAULT NULL,
    P_HESAPTIPI             IN KB_HESAPBILGILERI.HESAPTIPI%TYPE             DEFAULT NULL
)
AS
    V_RECORDUSER KB_HESAPBILGILERI.RECORDUSER%TYPE;
    V_RECORDDATE KB_HESAPBILGILERI.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    UPDATE KB_HESAPBILGILERI
    SET
        HESAPADI           = NVL(P_HESAPADI, HESAPADI),
        HESAPNO            = NVL(P_HESAPNO, HESAPNO),
        IBAN               = NVL(P_IBAN, IBAN),
        BAKIYE             = NVL(P_BAKIYE, BAKIYE),
        SUBESUBEKODU       = NVL(P_SUBESUBEKODU, SUBESUBEKODU),
        DOVIZCINSI         = NVL(P_DOVIZCINSI, DOVIZCINSI),
        HESAPDURUMKODU     = NVL(P_HESAPDURUMKODU, HESAPDURUMKODU),
        MUSTERIBILGILERIID = NVL(P_MUSTERIBILGILERIID, MUSTERIBILGILERIID),
        HESAPTIPI          = NVL(P_HESAPTIPI, HESAPTIPI),
        RECORDUSER         = V_RECORDUSER,
        RECORDDATE         = V_RECORDDATE
    WHERE
        ID = P_ID;
END KB_HESAPBILGILERI_GUNCELLE;
/


CREATE OR REPLACE PROCEDURE KB_HESAPBILGILERI_GETIRBYIBAN
(
    P_IBAN      IN  KB_HESAPBILGILERI.IBAN%TYPE,
    P_SONUC     OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
    SELECT *
    FROM KB_HESAPBILGILERI
    WHERE IBAN = P_IBAN;
END;
/


CREATE OR REPLACE PROCEDURE KB_HESAPDASHBOARD
(
    P_BASLANGICTARIHI IN  DATE DEFAULT NULL,
    P_BITISTARIHI     IN  DATE DEFAULT NULL,
    P_SONUC           OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
    SELECT COUNT(*) AS HESAP_SAYISI,
           SUM(CASE WHEN HESAPDURUMKODU = 1 THEN 1 ELSE 0 END) AS AKTIFSAYI,
           SUM(CASE WHEN HESAPDURUMKODU = 2 THEN 1 ELSE 0 END) AS PASIFSAYI,
           SUM(CASE WHEN DOVIZCINSI = 1 THEN 1 ELSE 0 END) AS TLSAYI,
           SUM(CASE WHEN DOVIZCINSI = 2 THEN 1 ELSE 0 END) AS USDSAYI,
           SUM(CASE WHEN DOVIZCINSI = 3 THEN 1 ELSE 0 END) AS EURSAYI
    FROM KB_HESAPBILGILERI
    WHERE (P_BASLANGICTARIHI IS NULL OR TRUNC(HESAPACILISTARIHI) >= TRUNC(P_BASLANGICTARIHI))
      AND (P_BITISTARIHI IS NULL OR TRUNC(HESAPACILISTARIHI) <= TRUNC(P_BITISTARIHI));
END KB_HESAPDASHBOARD;
/