CREATE OR REPLACE PROCEDURE KB_PERSONEL_EKLE
(
    P_AD                IN  KB_PERSONEL.AD%TYPE,
    P_SOYAD             IN  KB_PERSONEL.SOYAD%TYPE,
    P_ROL               IN  KB_PERSONEL.ROL%TYPE,
    P_SIFRE             IN  KB_PERSONEL.SIFRE%TYPE,
    P_TCKN              IN  KB_PERSONEL.TCKN%TYPE,
    P_TELEFONNO         IN  KB_PERSONEL.TELEFONNO%TYPE,
    P_ADRES             IN  KB_PERSONEL.ADRES%TYPE,
    P_EPOSTA            IN  KB_PERSONEL.EPOSTA%TYPE,
    P_SUBEKODU          IN  KB_PERSONEL.SUBESUBEKODU%TYPE,
    P_DURUMKODU         IN  KB_PERSONEL.DURUMKODU%TYPE,
    P_RECORDUSER        IN  KB_PERSONEL.RECORDUSER%TYPE,

    P_ID                OUT KB_PERSONEL.ID%TYPE,
    P_SICIL             OUT KB_PERSONEL.SICIL%TYPE
)
AS
BEGIN
    INSERT INTO KB_PERSONEL
    (
        AD,
        SOYAD,
        ROL,
        SIFRE,
        TCKN,
        TELEFONNO,
        ADRES,
        EPOSTA,
        SUBESUBEKODU,
        DURUMKODU,
        RECORDUSER
    )
    VALUES
    (
        P_AD,
        P_SOYAD,
        P_ROL,
        P_SIFRE,
        P_TCKN,
        P_TELEFONNO,
        P_ADRES,
        P_EPOSTA,
        P_SUBEKODU,
        P_DURUMKODU,
        P_RECORDUSER
    )
    RETURNING ID, SICIL INTO P_ID, P_SICIL;
END ;
/



CREATE OR REPLACE PROCEDURE KB_PERSONEL_GETIRBYID(
    P_ID            IN  KB_PERSONEL.ID%TYPE,
    P_CURSOR        OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM KB_PERSONEL WHERE ID = P_ID;
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_LISTELE
(
    P_ID          IN  KB_PERSONEL.ID%TYPE,
    P_AD          IN  KB_PERSONEL.AD%TYPE,
    P_SOYAD       IN  KB_PERSONEL.SOYAD%TYPE,
    P_ROL         IN  KB_PERSONEL.ROL%TYPE,
    P_TCKN        IN  KB_PERSONEL.TCKN%TYPE,
    P_TELEFONNO   IN  KB_PERSONEL.TELEFONNO%TYPE,
    P_SUBEKODU    IN  KB_PERSONEL.SUBESUBEKODU%TYPE,
    P_ADRES        IN  KB_PERSONEL.ADRES%TYPE,
    P_EPOSTA       IN  KB_PERSONEL.EPOSTA%TYPE,
    P_DURUMKODU    IN  KB_PERSONEL.DURUMKODU%TYPE,
    P_CURSOR                OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR SELECT * FROM KB_PERSONEL
    WHERE
            (ID             = P_ID OR P_ID IS NULL)
        AND (AD             = P_AD IS NULL OR UPPER(AD) LIKE '%' || UPPER(P_AD) || '%')
        AND (SOYAD          = P_SOYAD IS NULL OR UPPER(SOYAD) LIKE '%' || (P_SOYAD) || '%')
        AND (ROL            = P_ROL OR P_ROL IS NULL)
        AND (TCKN           = P_TCKN OR P_TCKN IS NULL)
        AND (TELEFONNO      = P_TELEFONNO OR P_TELEFONNO IS NULL)
        AND (SUBESUBEKODU   = P_SUBEKODU OR P_SUBEKODU IS NULL)
        AND (ADRES          = P_ADRES IS NULL OR UPPER(ADRES) LIKE '%' || UPPER(P_ADRES) || '%')
        AND (EPOSTA         = P_EPOSTA OR P_EPOSTA IS NULL)
        AND (DURUMKODU      = P_DURUMKODU OR P_DURUMKODU IS NULL);
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_GUNCELLE(
    P_ID            IN KB_PERSONEL.ID%TYPE,
    P_AD            IN KB_PERSONEL.AD%TYPE              DEFAULT NULL,
    P_SOYAD         IN KB_PERSONEL.SOYAD%TYPE           DEFAULT NULL,
    P_ROL           IN KB_PERSONEL.ROL%TYPE             DEFAULT NULL,
    P_SIFRE         IN KB_PERSONEL.SIFRE%TYPE           DEFAULT NULL,
    P_TCKN          IN KB_PERSONEL.TCKN%TYPE            DEFAULT NULL,
    P_TELEFONNO     IN KB_PERSONEL.TELEFONNO%TYPE       DEFAULT NULL,
    P_ADRES         IN KB_PERSONEL.ADRES%TYPE           DEFAULT NULL,
    P_EPOSTA        IN KB_PERSONEL.EPOSTA%TYPE          DEFAULT NULL,
    P_SUBEKODU      IN KB_PERSONEL.SUBESUBEKODU%TYPE    DEFAULT NULL,
    P_DURUMKODU     IN KB_PERSONEL.DURUMKODU%TYPE       DEFAULT NULL,
    P_RECORDUSER    IN KB_PERSONEL.RECORDUSER%TYPE      DEFAULT NULL
)
AS
BEGIN
    UPDATE KB_PERSONEL
    SET AD              = NVL(P_AD, AD),
        SOYAD           = NVL(P_SOYAD, SOYAD),
        ROL             = NVL(P_ROL, ROL),
        SIFRE           = NVL(P_SIFRE, SIFRE),
        TCKN            = NVL(P_TCKN, TCKN),
        TELEFONNO       = NVL(P_TELEFONNO, TELEFONNO),
        ADRES           = NVL(P_ADRES, ADRES),
        EPOSTA          = NVL(P_EPOSTA, EPOSTA),
        SUBESUBEKODU    = NVL(P_SUBEKODU, SUBESUBEKODU),
        DURUMKODU       = NVL(P_DURUMKODU, DURUMKODU),
        RECORDUSER      = NVL(P_RECORDUSER, RECORDUSER)
    WHERE ID = P_ID;
END ;
/


CREATE OR REPLACE PROCEDURE KB_PERSONEL_SIL
(
    P_ID IN KB_PERSONEL.ID%TYPE
)
AS
BEGIN
    DELETE FROM KB_PERSONEL WHERE ID = P_ID;
END ;
/


