EXEC P_INSERT_KB_MUSTERIBILGILERI('AYBEY', 'NURÇİN', 'aybey.nurcin@vakifbank.com', 'sifre123', TO_DATE('1990-01-01', 'YYYY-MM-DD'), '05376255784', 12345678901, 1, 1, 'S0010', 1, 'Yönetici', SYSDATE);
EXEC P_SELECT_KB_MUSTERIBILGILERI(10);
EXEC P_UPDATE_KB_MUSTERIBILGILERI(10, 'Ahmet', 'Taban', 'ahmet.taban@vakifbank.com', 'sifre456', TO_DATE('1985-05-15', 'YYYY-MM-DD'), '05313313131', 12345678902, 0, 0, 'S0010', 0, 'Çalışan', SYSDATE);
EXEC P_DELETE_KB_MUSTERIBILGILERI(10);


CREATE OR REPLACE PROCEDURE P_INSERT_KB_MUSTERIBILGILERI
(
    P_AD IN VARCHAR2,
    P_SOYAD IN VARCHAR2,
    P_EPOSTA IN VARCHAR2,
    P_SIFRE IN VARCHAR2,
    P_DOGUMTARIHI IN DATE,
    P_TELEFONNO IN VARCHAR2,
    P_TCKN IN NUMBER,
    P_CINSIYET IN NUMBER,
    P_MUSTERITIPI IN NUMBER,
    P_SUBESUBEKODU IN VARCHAR2,
    P_DURUMKODU IN NUMBER,
    P_UNVAN IN VARCHAR2,
    P_KAYITOLUSTURMATARIHI IN DATE
)
AS
BEGIN
    INSERT INTO
    KB_MUSTERIBILGILERI (AD, SOYAD, EPOSTA, SIFRE, DOGUMTARIHI, TELEFONNO, TCKN, CINSIYET, MUSTERITIPI, SUBESUBEKODU, DURUMKODU, UNVAN, KAYITOLUSTURMATARIHI)
    VALUES (P_AD, P_SOYAD, P_EPOSTA, P_SIFRE, P_DOGUMTARIHI, P_TELEFONNO, P_TCKN, P_CINSIYET, P_MUSTERITIPI, P_SUBESUBEKODU, P_DURUMKODU, P_UNVAN, P_KAYITOLUSTURMATARIHI);
END P_INSERT_KB_MUSTERIBILGILERI;
/

CREATE OR REPLACE PROCEDURE P_SELECT_KB_MUSTERIBILGILERI
(
    P_ID IN NUMBER
)
AS
BEGIN
    FOR MUSTERI_KAYDI IN (SELECT * FROM KB_MUSTERIBILGILERI WHERE ID = P_ID) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || MUSTERI_KAYDI.ID);
        DBMS_OUTPUT.PUT_LINE('AD: ' || MUSTERI_KAYDI.AD);
        DBMS_OUTPUT.PUT_LINE('SOYAD: ' || MUSTERI_KAYDI.SOYAD);
        DBMS_OUTPUT.PUT_LINE('EPOSTA: ' || MUSTERI_KAYDI.EPOSTA);
        DBMS_OUTPUT.PUT_LINE('SIFRE: ' || MUSTERI_KAYDI.SIFRE);
        DBMS_OUTPUT.PUT_LINE('DOGUMTARIHI: ' || MUSTERI_KAYDI.DOGUMTARIHI);
        DBMS_OUTPUT.PUT_LINE('TELEFONNO: ' || MUSTERI_KAYDI.TELEFONNO);
        DBMS_OUTPUT.PUT_LINE('TCKN: ' || MUSTERI_KAYDI.TCKN);
        DBMS_OUTPUT.PUT_LINE('CINSIYET: ' || MUSTERI_KAYDI.CINSIYET);
        DBMS_OUTPUT.PUT_LINE('MUSTERITIPI: ' || MUSTERI_KAYDI.MUSTERITIPI);
        DBMS_OUTPUT.PUT_LINE('SUBESUBEKODU: ' || MUSTERI_KAYDI.SUBESUBEKODU);
        DBMS_OUTPUT.PUT_LINE('DURUMKODU: ' || MUSTERI_KAYDI.DURUMKODU);
        DBMS_OUTPUT.PUT_LINE('UNVAN: ' || MUSTERI_KAYDI.UNVAN);
        DBMS_OUTPUT.PUT_LINE('KAYITOLUSTURMATARIHI: ' || MUSTERI_KAYDI.KAYITOLUSTURMATARIHI);
    END LOOP;
END P_SELECT_KB_MUSTERIBILGILERI;
/

CREATE OR REPLACE PROCEDURE P_UPDATE_KB_MUSTERIBILGILERI
(
    P_ID IN NUMBER,
    P_AD IN VARCHAR2,
    P_SOYAD IN VARCHAR2,
    P_EPOSTA IN VARCHAR2,
    P_SIFRE IN VARCHAR2,
    P_DOGUMTARIHI IN DATE,
    P_TELEFONNO IN VARCHAR2,
    P_TCKN IN NUMBER,
    P_CINSIYET IN NUMBER,
    P_MUSTERITIPI IN NUMBER,
    P_SUBESUBEKODU IN VARCHAR2,
    P_DURUMKODU IN NUMBER,
    P_UNVAN IN VARCHAR2
)
AS
BEGIN
    UPDATE KB_MUSTERIBILGILERI
    SET AD = P_AD,
        SOYAD = P_SOYAD,
        EPOSTA = P_EPOSTA,
        SIFRE = P_SIFRE,
        DOGUMTARIHI = P_DOGUMTARIHI,
        TELEFONNO = P_TELEFONNO,
        TCKN = P_TCKN,
        CINSIYET = P_CINSIYET,
        MUSTERITIPI = P_MUSTERITIPI,
        SUBESUBEKODU = P_SUBESUBEKODU,
        DURUMKODU = P_DURUMKODU,
        UNVAN = P_UNVAN
    WHERE ID = P_ID;
END P_UPDATE_KB_MUSTERIBILGILERI;
/

CREATE OR REPLACE PROCEDURE P_DELETE_KB_MUSTERIBILGILERI
(
    P_ID IN NUMBER
)
AS
BEGIN
    DELETE FROM KB_MUSTERIBILGILERI WHERE ID = P_ID;
END P_DELETE_KB_MUSTERIBILGILERI;
/