CREATE OR REPLACE PROCEDURE KB_MUSTERIBILGILERI_EKLE
(
    P_AD                    IN  KB_MUSTERIBILGILERI.AD%TYPE,
    P_SOYAD                 IN  KB_MUSTERIBILGILERI.SOYAD%TYPE,
    P_EPOSTA                IN  KB_MUSTERIBILGILERI.EPOSTA%TYPE,
    P_DOGUMTARIHI           IN  KB_MUSTERIBILGILERI.DOGUMTARIHI%TYPE,
    P_TELEFONNO             IN  KB_MUSTERIBILGILERI.TELEFONNO%TYPE,
    P_TCKN                  IN  KB_MUSTERIBILGILERI.TCKN%TYPE,
    P_CINSIYET              IN  KB_MUSTERIBILGILERI.CINSIYET%TYPE,
    P_VKN                   IN  KB_MUSTERIBILGILERI.VKN%TYPE,
    P_MUSTERITIPI           IN  KB_MUSTERIBILGILERI.MUSTERITIPI%TYPE,
    P_SUBESUBEKODU          IN  KB_MUSTERIBILGILERI.SUBESUBEKODU%TYPE,
    P_DURUMKODU             IN  KB_MUSTERIBILGILERI.DURUMKODU%TYPE,
    P_UNVAN                 IN  KB_MUSTERIBILGILERI.UNVAN%TYPE,
    P_RECORDUSER            IN  KB_MUSTERIBILGILERI.RECORDUSER%TYPE,
    P_ID                    OUT KB_MUSTERIBILGILERI.ID%TYPE,
    P_KAYITOLUSTURMATARIHI  OUT KB_MUSTERIBILGILERI.KAYITOLUSTURMATARIHI%TYPE
)
AS
    V_RECORDUSER KB_MUSTERIBILGILERI.RECORDUSER%TYPE;
    V_RECORDDATE KB_MUSTERIBILGILERI.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    INSERT INTO KB_MUSTERIBILGILERI
    (
        AD, SOYAD, EPOSTA, DOGUMTARIHI, TELEFONNO, TCKN,
        CINSIYET, VKN, MUSTERITIPI, SUBESUBEKODU, DURUMKODU,
        UNVAN, RECORDUSER, RECORDDATE
    )
    VALUES
    (
        P_AD, P_SOYAD, P_EPOSTA, P_DOGUMTARIHI, P_TELEFONNO, P_TCKN,
        P_CINSIYET, P_VKN, P_MUSTERITIPI, P_SUBESUBEKODU, P_DURUMKODU,
        P_UNVAN, V_RECORDUSER, V_RECORDDATE
    )
    RETURNING ID, KAYITOLUSTURMATARIHI
         INTO P_ID, P_KAYITOLUSTURMATARIHI;
END KB_MUSTERIBILGILERI_EKLE;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIBILGILERI_GETIRBYID
(
    P_ID    IN  KB_MUSTERIBILGILERI.ID%TYPE,
    P_SONUC OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT *
          FROM KB_MUSTERIBILGILERI
         WHERE ID = P_ID;
END KB_MUSTERIBILGILERI_GETIRBYID;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIBILGILERI_LISTELE
(
    P_ID                    IN  KB_MUSTERIBILGILERI.ID%TYPE,
    P_AD                    IN  KB_MUSTERIBILGILERI.AD%TYPE,
    P_SOYAD                 IN  KB_MUSTERIBILGILERI.SOYAD%TYPE,
    P_EPOSTA                IN  KB_MUSTERIBILGILERI.EPOSTA%TYPE,
    P_DOGUMTARIHIBASLANGIC  IN  KB_MUSTERIBILGILERI.DOGUMTARIHI%TYPE,
    P_DOGUMTARIHIBITIS      IN  KB_MUSTERIBILGILERI.DOGUMTARIHI%TYPE,
    P_TELEFONNO             IN  KB_MUSTERIBILGILERI.TELEFONNO%TYPE,
    P_TCKN                  IN  KB_MUSTERIBILGILERI.TCKN%TYPE,
    P_CINSIYET              IN  KB_MUSTERIBILGILERI.CINSIYET%TYPE,
    P_VKN                   IN  KB_MUSTERIBILGILERI.VKN%TYPE,
    P_MUSTERITIPI           IN  KB_MUSTERIBILGILERI.MUSTERITIPI%TYPE,
    P_SUBESUBEKODU          IN  KB_MUSTERIBILGILERI.SUBESUBEKODU%TYPE,
    P_DURUMKODU             IN  KB_MUSTERIBILGILERI.DURUMKODU%TYPE,
    P_UNVAN                 IN  KB_MUSTERIBILGILERI.UNVAN%TYPE,
    P_KAYITOLUSTURMATARIHI  IN  KB_MUSTERIBILGILERI.KAYITOLUSTURMATARIHI%TYPE,
    P_SONUC                 OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT *
          FROM KB_MUSTERIBILGILERI
         WHERE (P_ID IS NULL OR ID = P_ID)
           AND (P_AD IS NULL OR UPPER(AD) LIKE '%' || UPPER(P_AD) || '%')
           AND (P_SOYAD IS NULL OR UPPER(SOYAD) LIKE '%' || UPPER(P_SOYAD) || '%')
           AND (P_EPOSTA IS NULL OR UPPER(EPOSTA) LIKE '%' || UPPER(P_EPOSTA) || '%')
           AND (P_DOGUMTARIHIBASLANGIC IS NULL OR TRUNC(DOGUMTARIHI) >= TRUNC(P_DOGUMTARIHIBASLANGIC))
           AND (P_DOGUMTARIHIBITIS IS NULL OR TRUNC(DOGUMTARIHI) <= TRUNC(P_DOGUMTARIHIBITIS))
           AND (P_TELEFONNO IS NULL OR TELEFONNO LIKE '%' || P_TELEFONNO || '%')
           AND (P_TCKN IS NULL OR TCKN = P_TCKN)
           AND (P_CINSIYET IS NULL OR CINSIYET = P_CINSIYET)
           AND (P_VKN IS NULL OR VKN = P_VKN)
           AND (P_MUSTERITIPI IS NULL OR MUSTERITIPI = P_MUSTERITIPI)
           AND (P_SUBESUBEKODU IS NULL OR SUBESUBEKODU = P_SUBESUBEKODU)
           AND (P_DURUMKODU IS NULL OR DURUMKODU = P_DURUMKODU)
           AND (P_UNVAN IS NULL OR UPPER(UNVAN) = UPPER(P_UNVAN))
           AND (P_KAYITOLUSTURMATARIHI IS NULL
                OR TRUNC(KAYITOLUSTURMATARIHI) = TRUNC(P_KAYITOLUSTURMATARIHI));
END KB_MUSTERIBILGILERI_LISTELE;
/

-- Fiziksel silme korunmuştur. Silinen satır aynı tabloda audit bilgisi bırakamaz.
CREATE OR REPLACE PROCEDURE KB_MUSTERIBILGILERI_SIL
(
    P_ID IN KB_MUSTERIBILGILERI.ID%TYPE
)
AS
BEGIN
    DELETE FROM KB_MUSTERIBILGILERI
     WHERE ID = P_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20511, 'Silinecek müşteri bulunamadı.');
    END IF;
END KB_MUSTERIBILGILERI_SIL;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIBILGILERI_GUNCELLE
(
    P_ID            IN KB_MUSTERIBILGILERI.ID%TYPE,
    P_RECORDUSER    IN KB_MUSTERIBILGILERI.RECORDUSER%TYPE,
    P_AD            IN KB_MUSTERIBILGILERI.AD%TYPE           DEFAULT NULL,
    P_SOYAD         IN KB_MUSTERIBILGILERI.SOYAD%TYPE        DEFAULT NULL,
    P_EPOSTA        IN KB_MUSTERIBILGILERI.EPOSTA%TYPE       DEFAULT NULL,
    P_DOGUMTARIHI   IN KB_MUSTERIBILGILERI.DOGUMTARIHI%TYPE DEFAULT NULL,
    P_TELEFONNO     IN KB_MUSTERIBILGILERI.TELEFONNO%TYPE    DEFAULT NULL,
    P_TCKN          IN KB_MUSTERIBILGILERI.TCKN%TYPE         DEFAULT NULL,
    P_CINSIYET      IN KB_MUSTERIBILGILERI.CINSIYET%TYPE     DEFAULT NULL,
    P_VKN           IN KB_MUSTERIBILGILERI.VKN%TYPE          DEFAULT NULL,
    P_MUSTERITIPI   IN KB_MUSTERIBILGILERI.MUSTERITIPI%TYPE DEFAULT NULL,
    P_SUBESUBEKODU  IN KB_MUSTERIBILGILERI.SUBESUBEKODU%TYPE DEFAULT NULL,
    P_DURUMKODU     IN KB_MUSTERIBILGILERI.DURUMKODU%TYPE    DEFAULT NULL,
    P_UNVAN         IN KB_MUSTERIBILGILERI.UNVAN%TYPE        DEFAULT NULL
)
AS
    V_RECORDUSER KB_MUSTERIBILGILERI.RECORDUSER%TYPE;
    V_RECORDDATE KB_MUSTERIBILGILERI.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    UPDATE KB_MUSTERIBILGILERI
       SET AD           = NVL(P_AD, AD),
           SOYAD        = NVL(P_SOYAD, SOYAD),
           EPOSTA       = NVL(P_EPOSTA, EPOSTA),
           DOGUMTARIHI  = NVL(P_DOGUMTARIHI, DOGUMTARIHI),
           TELEFONNO    = NVL(P_TELEFONNO, TELEFONNO),
           TCKN         = NVL(P_TCKN, TCKN),
           CINSIYET     = NVL(P_CINSIYET, CINSIYET),
           VKN          = NVL(P_VKN, VKN),
           MUSTERITIPI  = NVL(P_MUSTERITIPI, MUSTERITIPI),
           SUBESUBEKODU = NVL(P_SUBESUBEKODU, SUBESUBEKODU),
           DURUMKODU    = NVL(P_DURUMKODU, DURUMKODU),
           UNVAN        = NVL(P_UNVAN, UNVAN),
           RECORDUSER   = V_RECORDUSER,
           RECORDDATE   = V_RECORDDATE
     WHERE ID = P_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20512, 'Güncellenecek müşteri bulunamadı.');
    END IF;
END KB_MUSTERIBILGILERI_GUNCELLE;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIILETISIM_GETIRBYMID
(
    P_ID    IN  KB_MUSTERIILETISIM.MUSTERIBILGILERIID%TYPE,
    P_SONUC OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT *
          FROM KB_MUSTERIILETISIM
         WHERE MUSTERIBILGILERIID = P_ID;
END KB_MUSTERIILETISIM_GETIRBYMID;
/

/*
 * NOT: Bu prosedür backend'de hiçbir yerden çağrılmıyor.
 * Müşteri iletişim güncellemesi KB_MUSTERI_ILETISIM_TAM_GUNCELLE
 * (M_prosedurler.sql) üzerinden yapılıyor (bkz. EMusteriIletisim.cs
 * Guncelle metodu). Silme yerine ESKI_ önekiyle işaretlenmiştir.
 */
CREATE OR REPLACE PROCEDURE ESKI_KB_MUSTERIILETISIM_GUNCELLE
(
    P_MUSTERIBILGILERIID IN KB_MUSTERIILETISIM.MUSTERIBILGILERIID%TYPE,
    P_RECORDUSER         IN KB_MUSTERIILETISIM.RECORDUSER%TYPE,
    P_TELEFONNO          IN KB_MUSTERIILETISIM.TELEFONNO%TYPE DEFAULT NULL,
    P_EVTELEFON          IN KB_MUSTERIILETISIM.EVTELEFON%TYPE DEFAULT NULL,
    P_ISTELEFON          IN KB_MUSTERIILETISIM.ISTELEFON%TYPE DEFAULT NULL,
    P_EPOSTA             IN KB_MUSTERIILETISIM.EPOSTA%TYPE    DEFAULT NULL,
    P_EVADRES            IN KB_MUSTERIILETISIM.EVADRES%TYPE  DEFAULT NULL,
    P_ISADRES            IN KB_MUSTERIILETISIM.ISADRES%TYPE  DEFAULT NULL
)
AS
    V_RECORDUSER KB_MUSTERIILETISIM.RECORDUSER%TYPE;
    V_RECORDDATE KB_MUSTERIILETISIM.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    UPDATE KB_MUSTERIILETISIM
       SET TELEFONNO = NVL(P_TELEFONNO, TELEFONNO),
           EVTELEFON = NVL(P_EVTELEFON, EVTELEFON),
           ISTELEFON = NVL(P_ISTELEFON, ISTELEFON),
           EPOSTA    = NVL(P_EPOSTA, EPOSTA),
           EVADRES   = NVL(P_EVADRES, EVADRES),
           ISADRES   = NVL(P_ISADRES, ISADRES),
           RECORDUSER = V_RECORDUSER,
           RECORDDATE = V_RECORDDATE
     WHERE MUSTERIBILGILERIID = P_MUSTERIBILGILERIID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20513, 'Güncellenecek müşteri iletişim kaydı bulunamadı.');
    END IF;
END ESKI_KB_MUSTERIILETISIM_GUNCELLE;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIILETISIM_EKLE
(
    P_MUSTERIBILGILERIID IN  KB_MUSTERIILETISIM.MUSTERIBILGILERIID%TYPE,
    P_TELEFONNO          IN  KB_MUSTERIILETISIM.TELEFONNO%TYPE,
    P_EVTELEFON          IN  KB_MUSTERIILETISIM.EVTELEFON%TYPE,
    P_ISTELEFON          IN  KB_MUSTERIILETISIM.ISTELEFON%TYPE,
    P_EPOSTA             IN  KB_MUSTERIILETISIM.EPOSTA%TYPE,
    P_EVADRES            IN  KB_MUSTERIILETISIM.EVADRES%TYPE,
    P_ISADRES            IN  KB_MUSTERIILETISIM.ISADRES%TYPE,
    P_RECORDUSER         IN  KB_MUSTERIILETISIM.RECORDUSER%TYPE,
    P_ID                 OUT KB_MUSTERIILETISIM.ID%TYPE
)
AS
    V_RECORDUSER KB_MUSTERIILETISIM.RECORDUSER%TYPE;
    V_RECORDDATE KB_MUSTERIILETISIM.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    INSERT INTO KB_MUSTERIILETISIM
    (
        MUSTERIBILGILERIID, TELEFONNO, EVTELEFON, ISTELEFON,
        EPOSTA, EVADRES, ISADRES, RECORDUSER, RECORDDATE
    )
    VALUES
    (
        P_MUSTERIBILGILERIID, P_TELEFONNO, P_EVTELEFON, P_ISTELEFON,
        P_EPOSTA, P_EVADRES, P_ISADRES, V_RECORDUSER, V_RECORDDATE
    )
    RETURNING ID INTO P_ID;
END KB_MUSTERIILETISIM_EKLE;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERIDASHBOARD
(
    P_BASLANGICTARIHI IN  DATE DEFAULT NULL,
    P_BITISTARIHI     IN  DATE DEFAULT NULL,
    P_SONUC           OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT COUNT(*) AS MUSTERI_SAYISI,
               NVL(SUM(CASE WHEN MUSTERITIPI = 1 THEN 1 ELSE 0 END), 0) AS BIREYSELSAYI,
               NVL(SUM(CASE WHEN MUSTERITIPI = 2 THEN 1 ELSE 0 END), 0) AS KURUMSALSAYI,
               NVL(SUM(CASE WHEN DURUMKODU = 1 THEN 1 ELSE 0 END), 0) AS AKTIFSAYI,
               NVL(SUM(CASE WHEN DURUMKODU = 2 THEN 1 ELSE 0 END), 0) AS PASIFSAYI,
               MAX(AD || ' ' || SOYAD) KEEP (DENSE_RANK LAST ORDER BY KAYITOLUSTURMATARIHI) AS SON_MUSTERI_ADSOYAD
          FROM KB_MUSTERIBILGILERI
         WHERE (P_BASLANGICTARIHI IS NULL OR TRUNC(KAYITOLUSTURMATARIHI) >= TRUNC(P_BASLANGICTARIHI))
           AND (P_BITISTARIHI IS NULL OR TRUNC(KAYITOLUSTURMATARIHI) <= TRUNC(P_BITISTARIHI));
END KB_MUSTERIDASHBOARD;
/

CREATE OR REPLACE PROCEDURE KB_SUBEDASHBOARD
(
    P_BASLANGICTARIHI IN  DATE DEFAULT NULL,
    P_BITISTARIHI     IN  DATE DEFAULT NULL,
    P_SONUC           OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT
            COUNT(*) AS SUBE_SAYISI,

            NVL(
                SUM(
                    CASE
                        WHEN SUBEDURUMKODU = 1 THEN 1
                        ELSE 0
                    END
                ),
                0
            ) AS AKTIFSAYI,

            NVL(
                SUM(
                    CASE
                        WHEN SUBEDURUMKODU = 2 THEN 1
                        ELSE 0
                    END
                ),
                0
            ) AS PASIFSAYI,

            MAX(SUBEADI) KEEP (DENSE_RANK LAST ORDER BY KAYITOLUSTURMATARIHI) AS SON_SUBE_ADI

        FROM KB_SUBE
        WHERE
            (
                P_BASLANGICTARIHI IS NULL
                OR TRUNC(KAYITOLUSTURMATARIHI) >= TRUNC(P_BASLANGICTARIHI)
            )
            AND
            (
                P_BITISTARIHI IS NULL
                OR TRUNC(KAYITOLUSTURMATARIHI) <= TRUNC(P_BITISTARIHI)
            );
END KB_SUBEDASHBOARD;
/

CREATE OR REPLACE PROCEDURE KB_PERSONELDASHBOARD
(
    P_BASLANGICTARIHI IN  DATE DEFAULT NULL,
    P_BITISTARIHI     IN  DATE DEFAULT NULL,
    P_SONUC           OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT
            COUNT(*) AS PERSONEL_SAYISI,

            NVL(
                SUM(
                    CASE
                        WHEN DURUMKODU = 1 THEN 1
                        ELSE 0
                    END
                ),
                0
            ) AS AKTIFSAYI,

            NVL(
                SUM(
                    CASE
                        WHEN DURUMKODU = 2 THEN 1
                        ELSE 0
                    END
                ),
                0
            ) AS PASIFSAYI,

            MAX(AD || ' ' || SOYAD) KEEP (DENSE_RANK LAST ORDER BY KAYITOLUSTURMATARIHI) AS SON_PERSONEL_ADSOYAD

        FROM KB_PERSONEL
        WHERE
            (
                P_BASLANGICTARIHI IS NULL
                OR TRUNC(KAYITOLUSTURMATARIHI) >=
                    TRUNC(P_BASLANGICTARIHI)
            )
            AND
            (
                P_BITISTARIHI IS NULL
                OR TRUNC(KAYITOLUSTURMATARIHI) <=
                    TRUNC(P_BITISTARIHI)
            );
END KB_PERSONELDASHBOARD;
/

CREATE OR REPLACE PROCEDURE KB_HESAPHAREKETI_LISTELE
(
    P_HESAPBILGILERIID IN  KB_HESAPHAREKETI.HESAPBILGILERIID%TYPE,
    P_SONUC            OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR
        SELECT *
          FROM KB_HESAPHAREKETI
         WHERE HESAPBILGILERIID = P_HESAPBILGILERIID;
END KB_HESAPHAREKETI_LISTELE;
/