CREATE OR REPLACE PROCEDURE KB_SUBE_EKLE
(
    P_AD            IN  KB_SUBE.SUBEADI%TYPE,
    P_TELEFONNO     IN  KB_SUBE.SUBETELEFONNO%TYPE,
    P_ADRES         IN  KB_SUBE.SUBEADRES%TYPE,
    P_DURUMKODU     IN  KB_SUBE.SUBEDURUMKODU%TYPE,
    P_RECORDUSER    IN  KB_SUBE.RECORDUSER%TYPE,

    P_ID            OUT KB_SUBE.ID%TYPE,
    P_SUBEKODU      OUT KB_SUBE.SUBEKODU%TYPE
)
AS
BEGIN
    INSERT INTO KB_SUBE
    (
        SUBEADI,
        SUBETELEFONNO,
        SUBEADRES,
        SUBEDURUMKODU,
        RECORDUSER
    )
    VALUES
    (
        P_AD,
        P_TELEFONNO,
        P_ADRES,
        P_DURUMKODU,
        P_RECORDUSER
    )
    RETURNING ID, SUBEKODU INTO P_ID, P_SUBEKODU;
END KB_SUBE_EKLE;
/

select * from KB_SUBE;


/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_GETIRBYID(
    P_ID        IN KB_SUBE.ID%TYPE,

    P_SONUC     OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR SELECT * FROM KB_SUBE WHERE ID = P_ID;
END KB_SUBE_GETIRBYID;
/



CREATE OR REPLACE PROCEDURE KB_SUBE_LISTELE(
   P_ID             IN KB_SUBE.ID%TYPE,
   P_AD             IN KB_SUBE.SUBEADI%TYPE,
   P_SUBEKODU       IN KB_SUBE.SUBEKODU%TYPE,
   P_TELEFONNO      IN KB_SUBE.SUBETELEFONNO%TYPE,
   P_ADRES          IN KB_SUBE.SUBEADRES%TYPE,
   P_DURUMKODU      IN KB_SUBE.SUBEDURUMKODU%TYPE,
   
    P_SONUC         OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR SELECT * FROM KB_SUBE
    WHERE 
        (P_ID IS NULL OR ID = P_ID)
    AND (P_AD IS NULL OR UPPER(SUBEADI) LIKE '%' || UPPER(P_AD) || '%')
    AND (P_SUBEKODU IS NULL OR SUBEKODU = P_SUBEKODU)
    AND (P_TELEFONNO IS NULL OR SUBETELEFONNO = P_TELEFONNO)
    AND (P_ADRES IS NULL OR UPPER(SUBEADRES) LIKE '%' || UPPER(P_ADRES) || '%')
    AND (P_DURUMKODU IS NULL OR SUBEDURUMKODU = P_DURUMKODU);
END;
/


/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_SIL(
    P_ID IN KB_SUBE.ID%TYPE
)
AS
BEGIN
    DELETE FROM KB_SUBE WHERE ID = P_ID;
END;
/

/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_GUNCELLE(
    P_ID            IN KB_SUBE.ID%TYPE,
    P_AD            IN KB_SUBE.SUBEADI%TYPE         DEFAULT NULL,
    P_TELEFONNO     IN KB_SUBE.SUBETELEFONNO%TYPE   DEFAULT NULL,
    P_ADRES         IN KB_SUBE.SUBEADRES%TYPE       DEFAULT NULL,
    P_DURUMKODU     IN KB_SUBE.SUBEDURUMKODU%TYPE   DEFAULT NULL
)
AS
BEGIN
    UPDATE KB_SUBE
    SET SUBEADI         = NVL(P_AD, SUBEADI),
        SUBETELEFONNO   = NVL(P_TELEFONNO, SUBETELEFONNO),
        SUBEADRES       = NVL(P_ADRES, SUBEADRES),
        SUBEDURUMKODU   = NVL(P_DURUMKODU, SUBEDURUMKODU)
    WHERE ID = P_ID;
END;
/
