CREATE OR REPLACE PROCEDURE KB_SUBE_EKLE
(
    P_AD          IN  KB_SUBE.SUBEADI%TYPE,
    P_TELEFONNO   IN  KB_SUBE.SUBETELEFONNO%TYPE,
    P_ADRES       IN  KB_SUBE.SUBEADRES%TYPE,
    P_DURUMKODU   IN  KB_SUBE.SUBEDURUMKODU%TYPE,
    P_RECORDUSER  IN  KB_SUBE.RECORDUSER%TYPE,

    P_ID          OUT KB_SUBE.ID%TYPE,
    P_SUBEKODU    OUT KB_SUBE.SUBEKODU%TYPE
)
AS
    V_RECORDUSER  KB_SUBE.RECORDUSER%TYPE;
    V_RECORDDATE  KB_SUBE.RECORDDATE%TYPE;
BEGIN
    KB_AUDIT_BILGI_HAZIRLA
    (
        P_RECORDUSER       => P_RECORDUSER,
        P_DUZENLENMIS_USER => V_RECORDUSER,
        P_RECORDDATE       => V_RECORDDATE
    );

    INSERT INTO KB_SUBE
    (
        SUBEADI,
        SUBETELEFONNO,
        SUBEADRES,
        SUBEDURUMKODU,
        RECORDUSER,
        RECORDDATE
    )
    VALUES
    (
        P_AD,
        P_TELEFONNO,
        P_ADRES,
        P_DURUMKODU,
        V_RECORDUSER,
        V_RECORDDATE
    )
    RETURNING
        ID,
        SUBEKODU
    INTO
        P_ID,
        P_SUBEKODU;
END KB_SUBE_EKLE;
/

select * from KB_SUBE;


/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_GETIRBYID(
    P_ID        IN KB_SUBE.ID%TYPE,

    P_SONUC     OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR SELECT * FROM KB_SUBE WHERE ID = P_ID;
END KB_SUBE_GETIRBYID;
/



CREATE OR REPLACE PROCEDURE KB_SUBE_LISTELE(
   P_ID             IN KB_SUBE.ID%TYPE,
   P_AD             IN KB_SUBE.SUBEADI%TYPE,
   P_SUBEKODU       IN KB_SUBE.SUBEKODU%TYPE,
   P_TELEFONNO      IN KB_SUBE.SUBETELEFONNO%TYPE,
   P_ADRES          IN KB_SUBE.SUBEADRES%TYPE,
   P_DURUMKODU      IN KB_SUBE.SUBEDURUMKODU%TYPE,
   
    P_SONUC         OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_SONUC FOR SELECT * FROM KB_SUBE
    WHERE 
        (P_ID IS NULL OR ID = P_ID)
    AND (P_AD IS NULL OR UPPER(SUBEADI) LIKE '%' || UPPER(P_AD) || '%')
    AND (P_SUBEKODU IS NULL OR SUBEKODU = P_SUBEKODU)
    AND (P_TELEFONNO IS NULL OR SUBETELEFONNO = P_TELEFONNO)
    AND (P_ADRES IS NULL OR UPPER(SUBEADRES) LIKE '%' || UPPER(P_ADRES) || '%')
    AND (P_DURUMKODU IS NULL OR SUBEDURUMKODU = P_DURUMKODU);
END;
/


/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_SIL(
    P_ID IN KB_SUBE.ID%TYPE
)
AS
BEGIN
    DELETE FROM KB_SUBE WHERE ID = P_ID;
END;
/

/*---------------------------------------------------------------------------------------------------------------*/

CREATE OR REPLACE PROCEDURE KB_SUBE_GUNCELLE(
    P_ID            IN KB_SUBE.ID%TYPE,
    P_AD            IN KB_SUBE.SUBEADI%TYPE         DEFAULT NULL,
    P_TELEFONNO     IN KB_SUBE.SUBETELEFONNO%TYPE   DEFAULT NULL,
    P_ADRES         IN KB_SUBE.SUBEADRES%TYPE       DEFAULT NULL,
    P_DURUMKODU     IN KB_SUBE.SUBEDURUMKODU%TYPE   DEFAULT NULL
)
AS
BEGIN
    UPDATE KB_SUBE
    SET SUBEADI         = NVL(P_AD, SUBEADI),
        SUBETELEFONNO   = NVL(P_TELEFONNO, SUBETELEFONNO),
        SUBEADRES       = NVL(P_ADRES, SUBEADRES),
        SUBEDURUMKODU   = NVL(P_DURUMKODU, SUBEDURUMKODU)
    WHERE ID = P_ID;
END;
/

CREATE OR REPLACE PROCEDURE KB_MUSTERI_TAM_EKLE
(
    /* MÜŞTERİ BİLGİLERİ */

    P_AD                   IN KB_MUSTERIBILGILERI.AD%TYPE,
    P_SOYAD                IN KB_MUSTERIBILGILERI.SOYAD%TYPE,
    P_EPOSTA               IN KB_MUSTERIBILGILERI.EPOSTA%TYPE,
    P_DOGUMTARIHI          IN KB_MUSTERIBILGILERI.DOGUMTARIHI%TYPE,
    P_TELEFONNO            IN KB_MUSTERIBILGILERI.TELEFONNO%TYPE,
    P_TCKN                 IN KB_MUSTERIBILGILERI.TCKN%TYPE,
    P_CINSIYET             IN KB_MUSTERIBILGILERI.CINSIYET%TYPE,
    P_VKN                  IN KB_MUSTERIBILGILERI.VKN%TYPE,
    P_MUSTERITIPI          IN KB_MUSTERIBILGILERI.MUSTERITIPI%TYPE,
    P_SUBESUBEKODU         IN KB_MUSTERIBILGILERI.SUBESUBEKODU%TYPE,
    P_DURUMKODU            IN KB_MUSTERIBILGILERI.DURUMKODU%TYPE,
    P_UNVAN                IN KB_MUSTERIBILGILERI.UNVAN%TYPE,

    /* İLETİŞİM BİLGİLERİ */

    P_EVTELEFON            IN KB_MUSTERIILETISIM.EVTELEFON%TYPE,
    P_ISTELEFON            IN KB_MUSTERIILETISIM.ISTELEFON%TYPE,
    P_EVADRES              IN KB_MUSTERIILETISIM.EVADRES%TYPE,
    P_ISADRES              IN KB_MUSTERIILETISIM.ISADRES%TYPE,

    /* OLUŞAN DEĞERLER */

    P_MUSTERI_ID           OUT KB_MUSTERIBILGILERI.ID%TYPE,
    P_ILETISIM_ID          OUT KB_MUSTERIILETISIM.ID%TYPE,
    P_KAYITOLUSTURMATARIHI OUT KB_MUSTERIBILGILERI.KAYITOLUSTURMATARIHI%TYPE
)
AS
BEGIN

    /* 1. MÜŞTERİYİ EKLE */

    KB_MUSTERIBILGILERI_EKLE
    (
        P_AD                   => P_AD,
        P_SOYAD                => P_SOYAD,
        P_EPOSTA               => P_EPOSTA,
        P_DOGUMTARIHI          => P_DOGUMTARIHI,
        P_TELEFONNO            => P_TELEFONNO,
        P_TCKN                 => P_TCKN,
        P_CINSIYET             => P_CINSIYET,
        P_VKN                  => P_VKN,
        P_MUSTERITIPI          => P_MUSTERITIPI,
        P_SUBESUBEKODU         => P_SUBESUBEKODU,
        P_DURUMKODU            => P_DURUMKODU,
        P_UNVAN                => P_UNVAN,

        P_ID                   => P_MUSTERI_ID,
        P_KAYITOLUSTURMATARIHI => P_KAYITOLUSTURMATARIHI
    );

    /* 2. AYNI MÜŞTERİNİN İLETİŞİM KAYDINI EKLE */

    KB_MUSTERIILETISIM_EKLE
    (
        P_MUSTERIBILGILERIID => P_MUSTERI_ID,

        /* Birinci ekrandan otomatik aktarılır. */
        P_TELEFONNO          => P_TELEFONNO,
        P_EPOSTA             => P_EPOSTA,

        P_EVTELEFON          => P_EVTELEFON,
        P_ISTELEFON          => P_ISTELEFON,
        P_EVADRES            => P_EVADRES,
        P_ISADRES            => P_ISADRES,

        P_ID                 => P_ILETISIM_ID
    );

END KB_MUSTERI_TAM_EKLE;
/

ALTER TABLE KB_MUSTERIILETISIM
ADD CONSTRAINT UK_KB_MUSTERIILETISIM_MID
UNIQUE (MUSTERIBILGILERIID);

SET SERVEROUTPUT ON;

DECLARE
    V_MUSTERI_ID
        KB_MUSTERIBILGILERI.ID%TYPE;

    V_ILETISIM_ID
        KB_MUSTERIILETISIM.ID%TYPE;

    V_KAYIT_TARIHI
        KB_MUSTERIBILGILERI.KAYITOLUSTURMATARIHI%TYPE;
BEGIN

    KB_MUSTERI_TAM_EKLE
    (
        P_AD                   => 'Test',
        P_SOYAD                => 'Musteri',
        P_EPOSTA               => 'tam.test.001@example.com',
        P_DOGUMTARIHI          => TO_DATE(
            '15.05.1995',
            'DD.MM.YYYY'
        ),
        P_TELEFONNO            => '05321234567',
        P_TCKN                 => '12345678901',
        P_CINSIYET             => 1,
        P_VKN                  => NULL,
        P_MUSTERITIPI          => 1,
        P_SUBESUBEKODU         => 'S0041',
        P_DURUMKODU            => 1,
        P_UNVAN                => NULL,

        P_EVTELEFON            => '02121234567',
        P_ISTELEFON            => '02129876543',
        P_EVADRES              => 'İstanbul Kadıköy',
        P_ISADRES              => 'İstanbul Şişli',

        P_MUSTERI_ID           => V_MUSTERI_ID,
        P_ILETISIM_ID          => V_ILETISIM_ID,
        P_KAYITOLUSTURMATARIHI => V_KAYIT_TARIHI
    );

    COMMIT;

    DBMS_OUTPUT.PUT_LINE(
        'Müşteri ID: ' || V_MUSTERI_ID
    );

    DBMS_OUTPUT.PUT_LINE(
        'İletişim ID: ' || V_ILETISIM_ID
    );

    DBMS_OUTPUT.PUT_LINE(
        'Kayıt tarihi: ' ||
        TO_CHAR(
            V_KAYIT_TARIHI,
            'DD.MM.YYYY HH24:MI:SS'
        )
    );

END;
/

SELECT
    ID,
    AD,
    SOYAD,
    EPOSTA,
    TELEFONNO,
    TCKN,
    MUSTERITIPI,
    SUBESUBEKODU,
    DURUMKODU
FROM KB_MUSTERIBILGILERI
WHERE EPOSTA = 'tam.test.001@example.com';

SELECT
    I.ID,
    I.MUSTERIBILGILERIID,
    I.TELEFONNO,
    I.EPOSTA,
    I.EVTELEFON,
    I.ISTELEFON,
    I.EVADRES,
    I.ISADRES
FROM KB_MUSTERIILETISIM I
WHERE I.MUSTERIBILGILERIID =
(
    SELECT M.ID
    FROM KB_MUSTERIBILGILERI M
    WHERE M.EPOSTA =
        'tam.test.001@example.com'
);

SELECT
    M.ID AS MUSTERI_ID,
    M.AD,
    M.SOYAD,
    M.EPOSTA AS MUSTERI_EPOSTA,
    M.TELEFONNO AS MUSTERI_TELEFON,

    I.ID AS ILETISIM_ID,
    I.EPOSTA AS ILETISIM_EPOSTA,
    I.TELEFONNO AS ILETISIM_TELEFON,
    I.EVTELEFON,
    I.ISTELEFON,
    I.EVADRES,
    I.ISADRES

FROM KB_MUSTERIBILGILERI M

LEFT JOIN KB_MUSTERIILETISIM I
    ON I.MUSTERIBILGILERIID = M.ID

WHERE M.EPOSTA =
    'tam.test.001@example.com';


CREATE OR REPLACE PROCEDURE
KB_MUSTERI_ILETISIM_TAM_GUNCELLE
(
    P_MUSTERIBILGILERIID
        IN KB_MUSTERIBILGILERI.ID%TYPE,

    P_TELEFONNO
        IN KB_MUSTERIBILGILERI.TELEFONNO%TYPE,

    P_EPOSTA
        IN KB_MUSTERIBILGILERI.EPOSTA%TYPE,

    P_EVTELEFON
        IN KB_MUSTERIILETISIM.EVTELEFON%TYPE,

    P_ISTELEFON
        IN KB_MUSTERIILETISIM.ISTELEFON%TYPE,

    P_EVADRES
        IN KB_MUSTERIILETISIM.EVADRES%TYPE,

    P_ISADRES
        IN KB_MUSTERIILETISIM.ISADRES%TYPE
)
AS
BEGIN

    /* MÜŞTERİ TABLOSUNDAKİ
       TELEFON VE E-POSTA */

    UPDATE KB_MUSTERIBILGILERI
    SET
        TELEFONNO = P_TELEFONNO,
        EPOSTA = P_EPOSTA
    WHERE
        ID = P_MUSTERIBILGILERIID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Müşteri bulunamadı.'
        );
    END IF;


    /* İLETİŞİM TABLOSUNDAKİ
       BÜTÜN İLETİŞİM BİLGİLERİ */

    UPDATE KB_MUSTERIILETISIM
    SET
        TELEFONNO = P_TELEFONNO,
        EPOSTA = P_EPOSTA,
        EVTELEFON = P_EVTELEFON,
        ISTELEFON = P_ISTELEFON,
        EVADRES = P_EVADRES,
        ISADRES = P_ISADRES
    WHERE
        MUSTERIBILGILERIID =
            P_MUSTERIBILGILERIID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'Müşteri iletişim kaydı bulunamadı.'
        );
    END IF;

END KB_MUSTERI_ILETISIM_TAM_GUNCELLE;
/

SELECT
    OBJECT_NAME,
    OBJECT_TYPE,
    STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME =
    'KB_MUSTERI_ILETISIM_TAM_GUNCELLE';

    SELECT
    M.ID AS MUSTERI_ID,
    M.EPOSTA AS MUSTERI_EPOSTA,
    M.TELEFONNO AS MUSTERI_TELEFON,

    I.ID AS ILETISIM_ID,
    I.EPOSTA AS ILETISIM_EPOSTA,
    I.TELEFONNO AS ILETISIM_TELEFON,
    I.EVTELEFON,
    I.ISTELEFON,
    I.EVADRES,
    I.ISADRES

FROM KB_MUSTERIBILGILERI M

LEFT JOIN KB_MUSTERIILETISIM I
    ON I.MUSTERIBILGILERIID = M.ID

WHERE M.ID = 69;

BEGIN

    KB_MUSTERI_ILETISIM_TAM_GUNCELLE
    (
        P_MUSTERIBILGILERIID => 69,

        P_TELEFONNO =>
            '05329998877',

        P_EPOSTA =>
            'tam.test.001.updated@example.com',

        P_EVTELEFON =>
            '02123334455',

        P_ISTELEFON =>
            '02126667788',

        P_EVADRES =>
            'İstanbul Üsküdar',

        P_ISADRES =>
            'İstanbul Ataşehir'
    );

    COMMIT;

END;
/

SELECT
    M.ID AS MUSTERI_ID,
    M.EPOSTA AS MUSTERI_EPOSTA,
    M.TELEFONNO AS MUSTERI_TELEFON,

    I.ID AS ILETISIM_ID,
    I.EPOSTA AS ILETISIM_EPOSTA,
    I.TELEFONNO AS ILETISIM_TELEFON,
    I.EVTELEFON,
    I.ISTELEFON,
    I.EVADRES,
    I.ISADRES

FROM KB_MUSTERIBILGILERI M

LEFT JOIN KB_MUSTERIILETISIM I
    ON I.MUSTERIBILGILERIID = M.ID

WHERE M.ID = 69;


/*Para Çekme ve Yatırma İşlemleri*/

CREATE OR REPLACE PROCEDURE KB_HESAP_CEK_YATIR
(
    P_HESAPID IN NUMBER,
    P_ISLEMTIPI IN NUMBER,
    P_TUTAR IN NUMBER,
    P_RECORDUSER IN VARCHAR2,
    P_HAREKETID OUT NUMBER,
    P_YENIBAKIYE OUT NUMBER
)
AS
    V_ONCEKIBAKIYE KB_HESAPBILGILERI.BAKIYE%TYPE;
    V_SONRAKIBAKIYE KB_HESAPBILGILERI.BAKIYE%TYPE;
    V_DOVIZCINSI KB_HESAPBILGILERI.DOVIZCINSI%TYPE;
    V_HESAPDURUMKODU KB_HESAPBILGILERI.HESAPDURUMKODU%TYPE;
BEGIN
    IF P_HESAPID IS NULL OR P_HESAPID <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Geçersiz hesap ID.');
    END IF;

    IF P_ISLEMTIPI IS NULL OR P_ISLEMTIPI NOT IN (1,2) THEN
        RAISE_APPLICATION_ERROR(-20002, 'İşlem tipi para yatırma veya para çekme olmalıdır.');
    END IF;

    IF P_TUTAR IS NULL OR P_TUTAR <= 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'İşlem tutarı sıfırdan büyük olmalıdır.');
    END IF;

    IF P_RECORDUSER IS NOT NULL AND LENGTH(P_RECORDUSER) > 10 THEN
        RAISE_APPLICATION_ERROR(-20004, 'İşlemi yapan kullanıcı en fazla 10 karakter olabilir.');
    END IF;

    BEGIN
        SELECT BAKIYE, DOVIZCINSI, HESAPDURUMKODU
        INTO V_ONCEKIBAKIYE, V_DOVIZCINSI, V_HESAPDURUMKODU
        FROM KB_HESAPBILGILERI
        WHERE ID = P_HESAPID
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20005, 'Hesap bulunamadı.');
    END;

    IF V_HESAPDURUMKODU <> 1 THEN
        RAISE_APPLICATION_ERROR(-20006, 'Yalnızca aktif hesaplarda işlem yapılabilir.');
    END IF;

    IF P_ISLEMTIPI = 1 THEN
        V_SONRAKIBAKIYE := V_ONCEKIBAKIYE + P_TUTAR;
    ELSE
        IF V_ONCEKIBAKIYE < P_TUTAR THEN
            RAISE_APPLICATION_ERROR(-20007, 'Hesap bakiyesi para çekme işlemi için yetersizdir.');
        END IF;

        V_SONRAKIBAKIYE := V_ONCEKIBAKIYE - P_TUTAR;
    END IF;

    UPDATE KB_HESAPBILGILERI
    SET BAKIYE = V_SONRAKIBAKIYE
    WHERE ID = P_HESAPID;

    INSERT INTO KB_HESAPHAREKETI
    (
        HESAPBILGILERIID,
        HAREKETTIPI,
        TUTAR,
        DOVIZCINSI,
        ONCEKIBAKIYE,
        SONRAKIBAKIYE,
        ISLEMTARIHI,
        RECORDUSER,
        RECORDDATE
    )
    VALUES
    (
        P_HESAPID,
        P_ISLEMTIPI,
        P_TUTAR,
        V_DOVIZCINSI,
        V_ONCEKIBAKIYE,
        V_SONRAKIBAKIYE,
        SYSTIMESTAMP,
        P_RECORDUSER,
        SYSTIMESTAMP
    )
    RETURNING ID INTO P_HAREKETID;

    P_YENIBAKIYE := V_SONRAKIBAKIYE;
END;
/

SELECT * FROM KB_HESAPHAREKETI;

SELECT OBJECT_NAME, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'KB_HESAP_CEK_YATIR';

SELECT ID, HESAPADI, BAKIYE, DOVIZCINSI, HESAPDURUMKODU
FROM KB_HESAPBILGILERI
ORDER BY ID;

DECLARE
    V_HAREKETID NUMBER;
    V_YENIBAKIYE NUMBER;
BEGIN
    KB_HESAP_CEK_YATIR
    (
        P_HESAPID => 14,
        P_ISLEMTIPI => 1,
        P_MIKTAR => 1000,
        P_RECORDUSER => 'TEST',
        P_HAREKETID => V_HAREKETID,
        P_YENIBAKIYE => V_YENIBAKIYE
    );

    DBMS_OUTPUT.PUT_LINE('Hareket ID: ' || V_HAREKETID);
    DBMS_OUTPUT.PUT_LINE('Yeni bakiye: ' || V_YENIBAKIYE);

    COMMIT;
END;


/

DECLARE
    V_HAREKETID NUMBER;
    V_YENIBAKIYE NUMBER;
BEGIN
    KB_HESAP_CEK_YATIR
    (
        P_HESAPID => 14,
        P_ISLEMTIPI => 2,
        P_MIKTAR => 250,
        P_RECORDUSER => 'TEST',
        P_HAREKETID => V_HAREKETID,
        P_YENIBAKIYE => V_YENIBAKIYE
    );

    DBMS_OUTPUT.PUT_LINE('Hareket ID: ' || V_HAREKETID);
    DBMS_OUTPUT.PUT_LINE('Yeni bakiye: ' || V_YENIBAKIYE);

    COMMIT;
END;
/


