create TABLE KB_SUBE(
    ID NUMBER PRIMARY KEY,
    SUBEADI VARCHAR2(50) NOT NULL,
    SUBEKODU VARCHAR2(20) UNIQUE NOT NULL,
    SUBETELEFONNO VARCHAR2(11) NOT NULL,
    SUBEADRES VARCHAR2(50),
    SUBEDURUMKODU NUMBER(1) CHECK (SUBEDURUMKODU IN (1, 2)) NOT NULL,
    RECORDUSER VARCHAR2(10),
    RECORDDATE DATE DEFAULT SYSDATE
);

CREATE TABLE KB_PERSONEL (
    ID NUMBER PRIMARY KEY,
    AD VARCHAR2(50) NOT NULL,
    SOYAD VARCHAR2(50) NOT NULL,
    ROL VARCHAR2(20) NOT NULL,
    SICIL VARCHAR2(6) NOT NULL UNIQUE,
    SIFRE VARCHAR2(50) NOT NULL,
    TCKN NUMBER(11) UNIQUE NOT NULL,
    TELEFONNO VARCHAR2(13) NOT NULL,
    ADRES VARCHAR2(50),
    EPOSTA VARCHAR2(25) NOT NULL,
    SUBESUBEKODU VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_SUBE FOREIGN KEY (SUBESUBEKODU) REFERENCES KB_SUBE(SUBEKODU),
    DURUMKODU NUMBER(1) CHECK (DURUMKODU IN (1, 2)) NOT NULL,
    RECORDUSER VARCHAR2(10),
    RECORDDATE DATE DEFAULT SYSDATE
);

/* KB_PERSONEL tablosundaki SICIL alanı 'KB_' ile başlamalıdır. */
/* KB'den sonra 4 haneli rakam gelmelidir. Örn: KB1234 */