CREATE TABLE KB_MUSTERIILETISIM(
    ID NUMBER PRIMARY KEY,
    ILETISIMTIPI NUMBER(1) CHECK (ILETISIMTIPI IN (1, 2, 3, 4, 5, 6)) NOT NULL,
    ILETISIM VARCHAR2(100) NOT NULL,
    MUSTERIBILGILERIID NUMBER NOT NULL,
    CONSTRAINT FK_KB_MUSTERIILETISIM_MUSTERIBILGILERIID FOREIGN KEY (MUSTERIBILGILERIID) REFERENCES KB_MUSTERIBILGILERI(ID) ON DELETE CASCADE,
    RECORDUSER VARCHAR2(10),
    RECORDDATE DATE DEFAULT SYSDATE
);