CREATE TABLE PROJE_MUSTERIILETISIM
(
    ID              NUMBER(19),
    EPOSTA          VARCHAR2(50),
    TELEFONNO       VARCHAR2(11),
    AD              VARCHAR2(50),
    SOYAD           VARCHAR2(50),
    ADRES            VARCHAR2(100),
    ILETISIMTIPI    NUMBER(1),
    MUSTERIID       NUMBER(19),
    RECORDUSER      VARCHAR2(10),
    RECORDDATE      DATE            DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_PROJE_MUSTERIILETISIM PRIMARY KEY (ID),

    CONSTRAINT CK_MUSTERIILETISIM_TIPI CHECK (ILETISIMTIPI IN (1, 2, 3)),

    CONSTRAINT FK_MUSTERIILETISIM_MUSTERI FOREIGN KEY (MUSTERIID) REFERENCES PROJE_MUSTERIBILGILERI (ID),

);

SELECT * FROM PROJE_MUSTERIBILGILERI;

DROP TABLE PROJE_ADMIN;

DROP TABLE PROJE_MUSTERIBILGILERI;

DROP TABLE PROJE_SUBELER;