/*KB_MUSTERIBILGILERI*/
SELECT * FROM KB_MUSTERIBILGILERI;
DELETE FROM KB_MUSTERIBILGILERI;
COMMIT;
DESC KB_MUSTERIBILGILERI;

/*KB_MUSTERIILETISIM*/
SELECT * FROM KB_MUSTERIILETISIM;
DELETE FROM KB_MUSTERIILETISIM;
COMMIT;
DESC KB_MUSTERIILETISIM;

/*KB_HESAPBILGILERI*/
SELECT * FROM KB_HESAPBILGILERI;
DELETE FROM KB_HESAPBILGILERI;
COMMIT;
DESC KB_HESAPBILGILERI;

/*KB_PARATRANSFERI*/
SELECT * FROM KB_PARATRANSFERI;
DELETE FROM KB_PARATRANSFERI;
COMMIT;
DESC KB_PARATRANSFERI;

/*KB_PERSONEL*/
SELECT * FROM KB_PERSONEL;
DELETE FROM KB_PERSONEL;
COMMIT;
DESC KB_PERSONEL;

/*KB_SUBE*/
SELECT * FROM KB_SUBE;
DELETE FROM KB_SUBE;
COMMIT;
DESC KB_SUBE;