/*KB_MUSTERIBILGILERI*/
SELECT * FROM KB_MUSTERIBILGILERI;
DESC KB_MUSTERIBILGILERI;

/*KB_MUSTERIILETISIM*/
SELECT * FROM KB_MUSTERIILETISIM;
DESC KB_MUSTERIILETISIM;

/*KB_HESAPBILGILERI*/
SELECT * FROM KB_HESAPBILGILERI;
DESC KB_HESAPBILGILERI;

/*KB_PARATRANSFERI*/
SELECT * FROM KB_PARATRANSFERI;
DESC KB_PARATRANSFERI;

/*KB_PERSONEL*/
SELECT * FROM KB_PERSONEL;
DESC KB_PERSONEL;

/*KB_SUBE*/
SELECT * FROM KB_SUBE;
DESC KB_SUBE;

/*KB_PARAMETRE*/
SELECT * FROM KB_PARAMETRE;
DESC KB_PARAMETRE;

/*Aktif durumdaki hesapları, bakiyesi en yüksek hesaptan başlayarak listeleyin.
 Yalnızca hesap adı, IBAN, bakiye ve döviz cinsi gösterilsin.*/

 SELECT HESAPADI, IBAN, BAKIYE, DOVIZCINSI
 FROM KB_HESAPBILGILERI
 WHERE HESAPDURUMKODU = 1
 ORDER BY BAKIYE DESC;


SELECT * 
FROM KB_HESAPBILGILERI 
WHERE HESAPDURUMKODU = 1 AND DOVIZCINSI = 1 AND BAKIYE > 10000 AND BAKIYE < 50000 
ORDER BY BAKIYE DESC;

SELECT * FROM KB_HESAPBILGILERI WHERE  HESAPDURUMKODU != 3 AND DOVIZCINSI != 1 ORDER BY BAKIYE DESC;

SELECT * FROM KB_HESAPBILGILERI WHERE UPPER(HESAPADI) LIKE '%MAAŞ%' AND HESAPDURUMKODU = 1;

