/*KB_MUSTERIBILGILERI*/
SELECT * FROM KB_MUSTERIBILGILERI;
DESC KB_MUSTERIBILGILERI;

/*KB_MUSTERIILETISIM*/
SELECT * FROM KB_MUSTERIILETISIM;
DESC KB_MUSTERIILETISIM;

/*KB_HESAPBILGILERI*/
SELECT * FROM KB_HESAPBILGILERI;
DESC KB_HESAPBILGILERI;

/*KB_PARATRANSFERI*/
SELECT * FROM KB_PARATRANSFERI;
DESC KB_PARATRANSFERI;

/*KB_PERSONEL*/
SELECT * FROM KB_PERSONEL;
DESC KB_PERSONEL;

/*KB_SUBE*/
SELECT * FROM KB_SUBE;
DESC KB_SUBE;

/*KB_PARAMETRE*/
SELECT * FROM KB_PARAMETRE;
DESC KB_PARAMETRE;