-- İlk hesabı aktif olan 50 bireysel müşteriye virman için ikinci aktif hesap
-- Toplam: 50 ayrı INSERT
-- HESAPNO: 1-4 şube | 5-12 HESAPACILISTARIHI (DDMMYYYY) | 13-16 sequence
-- IBAN: TR + 2 kontrol hanesi + 00069 + 0 + 16 haneli HESAPNO

DECLARE
    V_ID             NUMBER(19);
    V_MUSTERI_ID     NUMBER(19);
    V_SUBE_KODU      VARCHAR2(20);
    V_ACILIS_TARIHI  DATE;
    V_HESAP_NO       VARCHAR2(16);
    V_BBAN           VARCHAR2(22);
    V_IBAN           VARCHAR2(26);
    V_KONTROL        NUMBER;
    V_ADET           NUMBER;
BEGIN
    -- 1. ek hesap: musteri001@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri001@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 26875.35, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0001', V_ACILIS_TARIHI);

    -- 2. ek hesap: musteri002@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri002@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 28750.70, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0002', V_ACILIS_TARIHI);

    -- 3. ek hesap: musteri003@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri003@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 30626.05, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0003', V_ACILIS_TARIHI);

    -- 4. ek hesap: musteri004@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri004@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 32501.40, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0004', V_ACILIS_TARIHI);

    -- 5. ek hesap: musteri005@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri005@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 34376.75, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0005', V_ACILIS_TARIHI);

    -- 6. ek hesap: musteri006@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri006@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 36252.10, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0006', V_ACILIS_TARIHI);

    -- 7. ek hesap: musteri007@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri007@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 38127.45, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0007', V_ACILIS_TARIHI);

    -- 8. ek hesap: musteri008@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri008@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 40002.80, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0008', V_ACILIS_TARIHI);

    -- 9. ek hesap: musteri010@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri010@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 41878.15, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0010', V_ACILIS_TARIHI);

    -- 10. ek hesap: musteri011@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri011@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 43753.50, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0011', V_ACILIS_TARIHI);

    -- 11. ek hesap: musteri012@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri012@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 45628.85, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0012', V_ACILIS_TARIHI);

    -- 12. ek hesap: musteri013@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri013@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 47504.20, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0013', V_ACILIS_TARIHI);

    -- 13. ek hesap: musteri014@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri014@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 49379.55, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0014', V_ACILIS_TARIHI);

    -- 14. ek hesap: musteri015@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri015@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 51254.90, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0015', V_ACILIS_TARIHI);

    -- 15. ek hesap: musteri016@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri016@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 53130.25, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0016', V_ACILIS_TARIHI);

    -- 16. ek hesap: musteri017@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri017@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 55005.60, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0017', V_ACILIS_TARIHI);

    -- 17. ek hesap: musteri019@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri019@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 56880.95, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0019', V_ACILIS_TARIHI);

    -- 18. ek hesap: musteri020@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri020@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 58756.30, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0020', V_ACILIS_TARIHI);

    -- 19. ek hesap: musteri021@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri021@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 60631.65, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0021', V_ACILIS_TARIHI);

    -- 20. ek hesap: musteri022@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri022@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 62507.00, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0022', V_ACILIS_TARIHI);

    -- 21. ek hesap: musteri023@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri023@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 64382.35, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0023', V_ACILIS_TARIHI);

    -- 22. ek hesap: musteri024@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri024@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 66257.70, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0024', V_ACILIS_TARIHI);

    -- 23. ek hesap: musteri025@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri025@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 68133.05, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0025', V_ACILIS_TARIHI);

    -- 24. ek hesap: musteri026@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri026@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 70008.40, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0026', V_ACILIS_TARIHI);

    -- 25. ek hesap: musteri028@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri028@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 71883.75, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0028', V_ACILIS_TARIHI);

    -- 26. ek hesap: musteri029@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri029@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 73759.10, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0029', V_ACILIS_TARIHI);

    -- 27. ek hesap: musteri030@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri030@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 75634.45, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0030', V_ACILIS_TARIHI);

    -- 28. ek hesap: musteri031@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri031@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 77509.80, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0031', V_ACILIS_TARIHI);

    -- 29. ek hesap: musteri032@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri032@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 79385.15, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0032', V_ACILIS_TARIHI);

    -- 30. ek hesap: musteri033@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri033@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 81260.50, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0033', V_ACILIS_TARIHI);

    -- 31. ek hesap: musteri034@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri034@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 83135.85, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0034', V_ACILIS_TARIHI);

    -- 32. ek hesap: musteri035@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri035@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 85011.20, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0035', V_ACILIS_TARIHI);

    -- 33. ek hesap: musteri037@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri037@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 86886.55, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0037', V_ACILIS_TARIHI);

    -- 34. ek hesap: musteri038@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri038@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 88761.90, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0038', V_ACILIS_TARIHI);

    -- 35. ek hesap: musteri039@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri039@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 90637.25, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0039', V_ACILIS_TARIHI);

    -- 36. ek hesap: musteri040@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri040@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 92512.60, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0040', V_ACILIS_TARIHI);

    -- 37. ek hesap: musteri041@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri041@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 94387.95, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0041', V_ACILIS_TARIHI);

    -- 38. ek hesap: musteri042@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri042@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 96263.30, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0042', V_ACILIS_TARIHI);

    -- 39. ek hesap: musteri043@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri043@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 98138.65, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0043', V_ACILIS_TARIHI);

    -- 40. ek hesap: musteri044@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri044@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 100014.00, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0044', V_ACILIS_TARIHI);

    -- 41. ek hesap: musteri046@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri046@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 101889.35, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0046', V_ACILIS_TARIHI);

    -- 42. ek hesap: musteri047@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri047@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 103764.70, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0047', V_ACILIS_TARIHI);

    -- 43. ek hesap: musteri048@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri048@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 105640.05, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0048', V_ACILIS_TARIHI);

    -- 44. ek hesap: musteri049@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri049@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 107515.40, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0049', V_ACILIS_TARIHI);

    -- 45. ek hesap: musteri050@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri050@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 109390.75, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0050', V_ACILIS_TARIHI);

    -- 46. ek hesap: musteri051@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri051@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 111266.10, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0051', V_ACILIS_TARIHI);

    -- 47. ek hesap: musteri052@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri052@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 113141.45, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0052', V_ACILIS_TARIHI);

    -- 48. ek hesap: musteri053@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri053@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 115016.80, V_SUBE_KODU, 2, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0053', V_ACILIS_TARIHI);

    -- 49. ek hesap: musteri055@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri055@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman İkinci Hesabım', V_HESAP_NO, V_IBAN, 116892.15, V_SUBE_KODU, 1, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 1, 'KB0055', V_ACILIS_TARIHI);

    -- 50. ek hesap: musteri056@test.com
    SELECT ID, SUBESUBEKODU INTO V_MUSTERI_ID, V_SUBE_KODU
    FROM KB_MUSTERIBILGILERI WHERE EPOSTA = 'musteri056@test.com';

    V_ACILIS_TARIHI := SYSDATE;
    LOOP
        SELECT KB_HESAPBILGILERI_SEQ.NEXTVAL INTO V_ID FROM DUAL;
        V_HESAP_NO := LPAD(REGEXP_SUBSTR(V_SUBE_KODU, '[0-9]+$'), 4, '0')
                      || TO_CHAR(V_ACILIS_TARIHI, 'DDMMYYYY')
                      || LPAD(MOD(V_ID, 10000), 4, '0');
        SELECT COUNT(*) INTO V_ADET FROM KB_HESAPBILGILERI WHERE HESAPNO = V_HESAP_NO;
        EXIT WHEN V_ADET = 0;
    END LOOP;

    V_BBAN := '00069' || '0' || V_HESAP_NO;
    V_KONTROL := 98 - MOD(TO_NUMBER(V_BBAN || '292700'), 97);
    V_IBAN := 'TR' || LPAD(V_KONTROL, 2, '0') || V_BBAN;

    INSERT INTO KB_HESAPBILGILERI (ID, HESAPADI, HESAPNO, IBAN, BAKIYE, SUBESUBEKODU, DOVIZCINSI, HESAPACILISTARIHI, HESAPDURUMKODU, MUSTERIBILGILERIID, HESAPTIPI, RECORDUSER, RECORDDATE)
    VALUES (V_ID, 'Virman Birikim Hesabım', V_HESAP_NO, V_IBAN, 118767.50, V_SUBE_KODU, 3, V_ACILIS_TARIHI, 1, V_MUSTERI_ID, 2, 'KB0056', V_ACILIS_TARIHI);

    COMMIT;
END;
/

-- Kontrol: Eklenen 50 hesap ve sahiplerinin aktif hesap sayısı
SELECT
    M.ID AS MUSTERI_ID,
    M.EPOSTA,
    COUNT(H.ID) AS TOPLAM_HESAP_SAYISI,
    SUM(CASE WHEN H.HESAPDURUMKODU = 1 THEN 1 ELSE 0 END) AS AKTIF_HESAP_SAYISI
FROM KB_MUSTERIBILGILERI M
JOIN KB_HESAPBILGILERI H ON H.MUSTERIBILGILERIID = M.ID
WHERE M.ID IN (
    SELECT MUSTERIBILGILERIID FROM KB_HESAPBILGILERI
    WHERE HESAPADI IN ('Virman Birikim Hesabım', 'Virman İkinci Hesabım')
)
GROUP BY M.ID, M.EPOSTA
ORDER BY M.EPOSTA;

-- Hesap numarası ve IBAN kontrolü
SELECT
    H.ID, M.EPOSTA, H.HESAPNO,
    SUBSTR(H.HESAPNO, 1, 4) AS SUBE_HANELERI,
    SUBSTR(H.HESAPNO, 5, 8) AS TARIH_HANELERI,
    TO_CHAR(H.HESAPACILISTARIHI, 'DDMMYYYY') AS HESAP_ACILIS_TARIHI,
    SUBSTR(H.HESAPNO, 13, 4) AS SEQUENCE_HANELERI,
    H.IBAN, LENGTH(H.HESAPNO) AS HESAPNO_UZUNLUK, LENGTH(H.IBAN) AS IBAN_UZUNLUK
FROM KB_HESAPBILGILERI H
JOIN KB_MUSTERIBILGILERI M ON M.ID = H.MUSTERIBILGILERIID
WHERE H.HESAPADI IN ('Virman Birikim Hesabım', 'Virman İkinci Hesabım')
ORDER BY H.ID;

